// Generated by `rules_postgres/lean/Pg/Ir/Emit/CashArith.lean`.
// DO NOT EDIT BY HAND. Regenerate via
// `rules_postgres/tools/regen/regen-cash-arith.sh`.
//
// Cash-arithmetic V1 fmgr cluster: 6 functions =
// {pl, mi, mul_int4, div_int4} × {cash} (4 ops) +
// {larger, smaller} × {cash} (2 compare ops).
//
// Each body decodes operand(s), performs the operation
// (overflow-checked for pl/mi/mul_int4, zero-checked for div_int4,
// simple comparison for larger/smaller), and returns the Cash result.
// On overflow/division-by-zero, signals via the corresponding
// pg_ereport_* helper + returns Datum 0. This mirrors Postgres'
// ereport(ERROR, ...) path: the diff-test harness checks the
// (out, err) tuple round-trips against the vendored C oracle.

#![allow(clippy::missing_safety_doc)]

use pg_fcinfo::{
    decode_i32, decode_i64,
    encode_i64,
    pg_add_s64_overflow, pg_sub_s64_overflow, pg_mul_s64_overflow,
    pg_ereport_numeric_value_out_of_range, pg_ereport_division_by_zero,
    FunctionCallInfoBaseData,
};

#[no_mangle]
pub unsafe extern "C" fn cash_pl(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg1 = decode_i64(f.args[0].value);
    let arg2 = decode_i64(f.args[1].value);
    let mut result: i64 = 0;
    if pg_add_s64_overflow(arg1, arg2, &mut result) {
        pg_ereport_numeric_value_out_of_range();
        return 0;
    }
    encode_i64(result)
}

#[no_mangle]
pub unsafe extern "C" fn cash_mi(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg1 = decode_i64(f.args[0].value);
    let arg2 = decode_i64(f.args[1].value);
    let mut result: i64 = 0;
    if pg_sub_s64_overflow(arg1, arg2, &mut result) {
        pg_ereport_numeric_value_out_of_range();
        return 0;
    }
    encode_i64(result)
}

#[no_mangle]
pub unsafe extern "C" fn cash_mul_int4(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg1 = decode_i64(f.args[0].value);
    let arg2 = decode_i32(f.args[1].value);
    let mut result: i64 = 0;
    if pg_mul_s64_overflow(arg1, arg2 as i64, &mut result) {
        pg_ereport_numeric_value_out_of_range();
        return 0;
    }
    encode_i64(result)
}

#[no_mangle]
pub unsafe extern "C" fn cash_div_int4(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let c = decode_i64(f.args[0].value);
    let i = decode_i32(f.args[1].value);
    if i == 0 {
        pg_ereport_division_by_zero();
        return 0;
    }
    encode_i64(c / (i as i64))
}

#[no_mangle]
pub unsafe extern "C" fn cashlarger(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let c1 = decode_i64(f.args[0].value);
    let c2 = decode_i64(f.args[1].value);
    let result = if c1 > c2 { c1 } else { c2 };
    encode_i64(result)
}

#[no_mangle]
pub unsafe extern "C" fn cashsmaller(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let c1 = decode_i64(f.args[0].value);
    let c2 = decode_i64(f.args[1].value);
    let result = if c1 < c2 { c1 } else { c2 };
    encode_i64(result)
}
