// Generated by `rules_postgres/lean/Pg/Ir/Emit/Macaddr.lean`.
// DO NOT EDIT BY HAND. Regenerate via
// `rules_postgres/tools/regen/regen-macaddr.sh`.
//
// Source of truth: the macaddr comparison and hash cluster specs in
// `Pg.Ir.Emit.MacaddrCommon`. The comparison operators delegate to
// a 3-way comparison of high and low 3-byte groups (matching real Postgres'
// macaddr_cmp_internal); the hash operators use Jenkins/lookup3 hashing via
// pg_fcinfo's hash_bytes_6 / hash_bytes_6_extended helpers.
//
// 9 functions = 6 comparison ops + 1 cmp op + 2 hash ops.

#![allow(clippy::missing_safety_doc)]

use pg_fcinfo::{
    decode_i64, decode_macaddr_p,
    encode_bool, encode_i32, encode_u32, encode_u64,
    hash_bytes_6, hash_bytes_6_extended,
    FunctionCallInfoBaseData,
};

// ─── macaddr_cmp_internal helper ──

/// Mirror of Postgres' `macaddr_cmp_internal`: compares two 6-byte MAC addresses.
/// Returns -1, 0, or 1.
#[inline]
unsafe fn macaddr_cmp_internal(arg1: *const u8, arg2: *const u8) -> i32 {
    // hibits: (a<<16) | (b<<8) | c
    let h1 = ((*arg1 as u32) << 16) | ((*arg1.add(1) as u32) << 8) | (*arg1.add(2) as u32);
    let h2 = ((*arg2 as u32) << 16) | ((*arg2.add(1) as u32) << 8) | (*arg2.add(2) as u32);
    if h1 < h2 {
        return -1;
    } else if h1 > h2 {
        return 1;
    }
    // lobits: (d<<16) | (e<<8) | f
    let l1 = ((*arg1.add(3) as u32) << 16) | ((*arg1.add(4) as u32) << 8) | (*arg1.add(5) as u32);
    let l2 = ((*arg2.add(3) as u32) << 16) | ((*arg2.add(4) as u32) << 8) | (*arg2.add(5) as u32);
    if l1 < l2 {
        return -1;
    } else if l1 > l2 {
        return 1;
    }
    0
}

// ─── macaddr comparison ops (eq, ne, lt, le, gt, ge) ──

#[no_mangle]
pub unsafe extern "C" fn macaddr_eq(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg1 = decode_macaddr_p(f.args[0].value);
    let arg2 = decode_macaddr_p(f.args[1].value);
    let cmp_result = macaddr_cmp_internal(arg1, arg2);
    encode_bool(cmp_result == 0)
}

#[no_mangle]
pub unsafe extern "C" fn macaddr_ne(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg1 = decode_macaddr_p(f.args[0].value);
    let arg2 = decode_macaddr_p(f.args[1].value);
    let cmp_result = macaddr_cmp_internal(arg1, arg2);
    encode_bool(cmp_result != 0)
}

#[no_mangle]
pub unsafe extern "C" fn macaddr_lt(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg1 = decode_macaddr_p(f.args[0].value);
    let arg2 = decode_macaddr_p(f.args[1].value);
    let cmp_result = macaddr_cmp_internal(arg1, arg2);
    encode_bool(cmp_result < 0)
}

#[no_mangle]
pub unsafe extern "C" fn macaddr_le(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg1 = decode_macaddr_p(f.args[0].value);
    let arg2 = decode_macaddr_p(f.args[1].value);
    let cmp_result = macaddr_cmp_internal(arg1, arg2);
    encode_bool(cmp_result <= 0)
}

#[no_mangle]
pub unsafe extern "C" fn macaddr_gt(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg1 = decode_macaddr_p(f.args[0].value);
    let arg2 = decode_macaddr_p(f.args[1].value);
    let cmp_result = macaddr_cmp_internal(arg1, arg2);
    encode_bool(cmp_result > 0)
}

#[no_mangle]
pub unsafe extern "C" fn macaddr_ge(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg1 = decode_macaddr_p(f.args[0].value);
    let arg2 = decode_macaddr_p(f.args[1].value);
    let cmp_result = macaddr_cmp_internal(arg1, arg2);
    encode_bool(cmp_result >= 0)
}

// ─── macaddr 3-way comparison (cmp) ──

#[no_mangle]
pub unsafe extern "C" fn macaddr_cmp(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg1 = decode_macaddr_p(f.args[0].value);
    let arg2 = decode_macaddr_p(f.args[1].value);
    let cmp_result = macaddr_cmp_internal(arg1, arg2);
    encode_i32(cmp_result)
}

// ─── macaddr hash ops (hashmacaddr, hashmacaddrextended) ──

#[no_mangle]
pub unsafe extern "C" fn hashmacaddr(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let key = decode_macaddr_p(f.args[0].value);
    encode_u32(hash_bytes_6(key))
}

#[no_mangle]
pub unsafe extern "C" fn hashmacaddrextended(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let key = decode_macaddr_p(f.args[0].value);
    let seed: u64 = decode_i64(f.args[1].value) as u64;
    encode_u64(hash_bytes_6_extended(key, seed))
}
