// Generated by `rules_postgres/lean/Pg/Ir/Emit/Bytea.lean`.
// DO NOT EDIT BY HAND. Regenerate via
// `rules_postgres/tools/regen/regen-bytea.sh`.
//
// First varlena-using Pg.Ir cluster. Each family emits a pair:
//   1. A static internal helper (the algorithm).
//   2. The V1 fmgr stub (decode args + delegate + return).

#![allow(clippy::missing_safety_doc)]

use pg_fcinfo::{
    decode_bytea_p, encode_bool, encode_bytea_p, encode_i32,
    set_varsize_4b, toast_raw_datum_size,
    vardata_4b_mut, vardata_any, varsize_any_exhdr,
    FunctionCallInfoBaseData, VARHDRSZ,
};
use pg_palloc::palloc;

unsafe fn bytea_catenate(t1: *const u8, t2: *const u8) -> *mut u8 {
    let len1 = varsize_any_exhdr(t1);
    let len2 = varsize_any_exhdr(t2);

    // Postgres has `if (lenN < 0) lenN = 0;` paranoia checks;
    // with usize typing this is statically impossible.

    let total = len1 + len2 + VARHDRSZ;
    let result = palloc(total);

    set_varsize_4b(result, total);

    let payload = vardata_4b_mut(result);
    if len1 > 0 {
        std::ptr::copy_nonoverlapping(vardata_any(t1), payload, len1);
    }
    if len2 > 0 {
        std::ptr::copy_nonoverlapping(vardata_any(t2), payload.add(len1), len2);
    }

    result
}

#[no_mangle]
pub unsafe extern "C" fn byteacat(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let t1 = decode_bytea_p(f.args[0].value);
    let t2 = decode_bytea_p(f.args[1].value);
    encode_bytea_p(bytea_catenate(t1, t2))
}

#[no_mangle]
pub unsafe extern "C" fn byteaoctetlen(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let str = f.args[0].value;
    encode_i32((toast_raw_datum_size(str) - VARHDRSZ) as i32)
}

#[no_mangle]
pub unsafe extern "C" fn byteaeq(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg1 = f.args[0].value;
    let arg2 = f.args[1].value;
    let len1 = toast_raw_datum_size(arg1);
    let len2 = toast_raw_datum_size(arg2);
    let result = if len1 != len2 {
        false
    } else {
        let barg1 = decode_bytea_p(arg1);
        let barg2 = decode_bytea_p(arg2);
        let p1 = vardata_any(barg1);
        let p2 = vardata_any(barg2);
        let n = len1 - VARHDRSZ;
        std::slice::from_raw_parts(p1, n) == std::slice::from_raw_parts(p2, n)
    };
    encode_bool(result)
}
