/*
 * renamed_int_div.c — rename each vendored fmgr body to <fn>_orig
 * before compiling, so the test linker doesn't merge them with the
 * Rust crate's #[no_mangle] symbols. Mirrors pg_int4_arith's
 * renamed_int4_arith.c.
 *
 * Generated by hand to stay in sync with the family table in
 * `rules_postgres/lean/Pg/Ir/Emit/IntDivCommon.lean`.
 */

#define int2div  int2div_orig
#define int4div  int4div_orig
#define int8div  int8div_orig

#include "int_div.c"
