// Generated by `rules_postgres/lean/Pg/Ir/Emit/Text.lean`.
// DO NOT EDIT BY HAND. Regenerate via
// `rules_postgres/tools/regen/regen-text.sh`.
//
// Second varlena-using Pg.Ir cluster. Text reuses bytea's varlena
// codec at the Datum level. Each family emits a pair:
//   1. A static internal helper (the algorithm).
//   2. The V1 fmgr stub (decode args + delegate + return).

#![allow(clippy::missing_safety_doc)]

use pg_fcinfo::{
    decode_bytea_p, encode_bytea_p,
    set_varsize_4b,
    vardata_4b_mut, vardata_any, varsize_any_exhdr,
    FunctionCallInfoBaseData, VARHDRSZ,
};
use pg_palloc::palloc;

unsafe fn text_catenate(t1: *const u8, t2: *const u8) -> *mut u8 {
    let len1 = varsize_any_exhdr(t1);
    let len2 = varsize_any_exhdr(t2);

    let total = len1 + len2 + VARHDRSZ;
    let result = palloc(total);

    set_varsize_4b(result, total);

    let payload = vardata_4b_mut(result);
    if len1 > 0 {
        std::ptr::copy_nonoverlapping(vardata_any(t1), payload, len1);
    }
    if len2 > 0 {
        std::ptr::copy_nonoverlapping(vardata_any(t2), payload.add(len1), len2);
    }

    result
}

#[no_mangle]
pub unsafe extern "C" fn textcat(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let t1 = decode_bytea_p(f.args[0].value);
    let t2 = decode_bytea_p(f.args[1].value);
    encode_bytea_p(text_catenate(t1, t2))
}
