/*
 * renamed_int4_arith.c — rename each vendored fmgr body to <fn>_orig
 * before compiling, so the test linker doesn't merge them with the
 * Rust crate's #[no_mangle] symbols. Mirrors pg_int4_cmp's
 * renamed_int4_cmp.c.
 *
 * Generated by hand to stay in sync with the family table in
 * `rules_postgres/lean/Pg/Ir/Emit/IntArithCommon.lean`.
 */

#define int2pl  int2pl_orig
#define int2mi  int2mi_orig
#define int2mul int2mul_orig

#define int4pl  int4pl_orig
#define int4mi  int4mi_orig
#define int4mul int4mul_orig

#define int8pl  int8pl_orig
#define int8mi  int8mi_orig
#define int8mul int8mul_orig

#define int24pl  int24pl_orig
#define int24mi  int24mi_orig
#define int24mul int24mul_orig

#define int42pl  int42pl_orig
#define int42mi  int42mi_orig
#define int42mul int42mul_orig

#define int48pl  int48pl_orig
#define int48mi  int48mi_orig
#define int48mul int48mul_orig

#define int84pl  int84pl_orig
#define int84mi  int84mi_orig
#define int84mul int84mul_orig

#define int28pl  int28pl_orig
#define int28mi  int28mi_orig
#define int28mul int28mul_orig

#define int82pl  int82pl_orig
#define int82mi  int82mi_orig
#define int82mul int82mul_orig

#include "int4_arith.c"
