// Generated by `rules_postgres/lean/Pg/Ir/Emit/IntDiv.lean`.
// DO NOT EDIT BY HAND. Regenerate via
// `rules_postgres/tools/regen/regen-int-div.sh`.
//
// Integer-division V1 fmgr cluster: 3 functions = {int2div, int4div, int8div}.
//
// Each body decodes both operands, checks for division by zero
// (ERRCODE_DIVISION_BY_ZERO), checks for INT_MIN / -1 overflow
// (ERRCODE_NUMERIC_VALUE_OUT_OF_RANGE), and returns the quotient.
// On error, signals via pg_ereport_division_by_zero() or
// pg_ereport_numeric_value_out_of_range() + returning Datum 0.
// This mirrors Postgres' ereport(ERROR, ...) path: a real backend catches
// the longjmp at the SPI/transaction boundary; our Rust side just sets a
// TLS error flag and returns 0, with the diff-test harness checking the
// (out, err) tuple round-trips against the vendored C oracle.

#![allow(clippy::missing_safety_doc)]

use pg_fcinfo::{
    decode_i16, decode_i32, decode_i64,
    encode_i16, encode_i32, encode_i64,
    pg_ereport_division_by_zero, pg_ereport_numeric_value_out_of_range,
    FunctionCallInfoBaseData,
};

fn unlikely(cond: bool) -> bool { cond }

#[no_mangle]
pub unsafe extern "C" fn int2div(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg1 = decode_i16(f.args[0].value);
    let arg2 = decode_i16(f.args[1].value);
    if arg2 == 0 {
        pg_ereport_division_by_zero();
        return 0;
    }
    if arg2 == -1 {
        if unlikely(arg1 == i16::MIN) {
            pg_ereport_numeric_value_out_of_range();
            return 0;
        }
        let result = -arg1;
        return encode_i16(result);
    }
    let result = arg1 / arg2;
    encode_i16(result)
}

#[no_mangle]
pub unsafe extern "C" fn int4div(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg1 = decode_i32(f.args[0].value);
    let arg2 = decode_i32(f.args[1].value);
    if arg2 == 0 {
        pg_ereport_division_by_zero();
        return 0;
    }
    if arg2 == -1 {
        if unlikely(arg1 == i32::MIN) {
            pg_ereport_numeric_value_out_of_range();
            return 0;
        }
        let result = -arg1;
        return encode_i32(result);
    }
    let result = arg1 / arg2;
    encode_i32(result)
}

#[no_mangle]
pub unsafe extern "C" fn int8div(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg1 = decode_i64(f.args[0].value);
    let arg2 = decode_i64(f.args[1].value);
    if arg2 == 0 {
        pg_ereport_division_by_zero();
        return 0;
    }
    if arg2 == -1 {
        if unlikely(arg1 == i64::MIN) {
            pg_ereport_numeric_value_out_of_range();
            return 0;
        }
        let result = -arg1;
        return encode_i64(result);
    }
    let result = arg1 / arg2;
    encode_i64(result)
}
