// Generated by `rules_postgres/lean/Pg/Ir/Emit/IntUnary.lean`.
// DO NOT EDIT BY HAND. Regenerate via
// `rules_postgres/tools/regen/regen-int-unary.sh`.
//
// Integer unary V1 fmgr cluster: 6 functions = {um, abs} ×
// {int2, int4, int8}. Each body checks the single overflow
// edge (`arg == <ty>::MIN`) and ereports on hit, otherwise
// returns the negated / absolute value.

#![allow(clippy::missing_safety_doc)]

use pg_fcinfo::{
    decode_i16, decode_i32, decode_i64,
    encode_i16, encode_i32, encode_i64,
    pg_ereport_numeric_value_out_of_range, FunctionCallInfoBaseData,
};

#[no_mangle]
pub unsafe extern "C" fn int2um(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg = decode_i16(f.args[0].value);
    if arg == i16::MIN {
        pg_ereport_numeric_value_out_of_range();
        return 0;
    }
    encode_i16(-arg)
}

#[no_mangle]
pub unsafe extern "C" fn int4um(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg = decode_i32(f.args[0].value);
    if arg == i32::MIN {
        pg_ereport_numeric_value_out_of_range();
        return 0;
    }
    encode_i32(-arg)
}

#[no_mangle]
pub unsafe extern "C" fn int8um(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg = decode_i64(f.args[0].value);
    if arg == i64::MIN {
        pg_ereport_numeric_value_out_of_range();
        return 0;
    }
    let result: i64 = -arg;
    encode_i64(result)
}

#[no_mangle]
pub unsafe extern "C" fn int2abs(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg = decode_i16(f.args[0].value);
    if arg == i16::MIN {
        pg_ereport_numeric_value_out_of_range();
        return 0;
    }
    let result: i16 = if arg < 0 { -arg } else { arg };
    encode_i16(result)
}

#[no_mangle]
pub unsafe extern "C" fn int4abs(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg = decode_i32(f.args[0].value);
    if arg == i32::MIN {
        pg_ereport_numeric_value_out_of_range();
        return 0;
    }
    let result: i32 = if arg < 0 { -arg } else { arg };
    encode_i32(result)
}

#[no_mangle]
pub unsafe extern "C" fn int8abs(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg = decode_i64(f.args[0].value);
    if arg == i64::MIN {
        pg_ereport_numeric_value_out_of_range();
        return 0;
    }
    let result: i64 = if arg < 0 { -arg } else { arg };
    encode_i64(result)
}
