// Generated by `rules_postgres/lean/Pg/Ir/Emit/Uuid.lean`.
// DO NOT EDIT BY HAND. Regenerate via
// `rules_postgres/tools/regen/regen-uuid.sh`.
//
// Source of truth: the UUID comparison and hash cluster specs in
// `Pg.Ir.Emit.UuidCommon`. The comparison operators delegate to
// a memcmp-based comparison (matching real Postgres' uuid_internal_cmp);
// the hash operators use Jenkins/lookup3 hashing via pg_fcinfo's
// hash_bytes_16 / hash_bytes_16_extended helpers.
//
// 9 functions = 6 comparison ops + 1 cmp op + 2 hash ops.

#![allow(clippy::missing_safety_doc)]

use pg_fcinfo::{
    decode_i64, decode_uuid_p,
    encode_bool, encode_i32, encode_u32, encode_u64,
    hash_bytes_16, hash_bytes_16_extended,
    FunctionCallInfoBaseData,
};

// ─── UUID comparison ops (eq, ne, lt, le, gt, ge) ──

#[no_mangle]
pub unsafe extern "C" fn uuid_eq(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg1 = decode_uuid_p(f.args[0].value);
    let arg2 = decode_uuid_p(f.args[1].value);
    let cmp_result = unsafe {
        libc::memcmp(arg1 as *const libc::c_void, arg2 as *const libc::c_void, 16)
    };
    encode_bool(cmp_result == 0)
}

#[no_mangle]
pub unsafe extern "C" fn uuid_ne(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg1 = decode_uuid_p(f.args[0].value);
    let arg2 = decode_uuid_p(f.args[1].value);
    let cmp_result = unsafe {
        libc::memcmp(arg1 as *const libc::c_void, arg2 as *const libc::c_void, 16)
    };
    encode_bool(cmp_result != 0)
}

#[no_mangle]
pub unsafe extern "C" fn uuid_lt(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg1 = decode_uuid_p(f.args[0].value);
    let arg2 = decode_uuid_p(f.args[1].value);
    let cmp_result = unsafe {
        libc::memcmp(arg1 as *const libc::c_void, arg2 as *const libc::c_void, 16)
    };
    encode_bool(cmp_result < 0)
}

#[no_mangle]
pub unsafe extern "C" fn uuid_le(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg1 = decode_uuid_p(f.args[0].value);
    let arg2 = decode_uuid_p(f.args[1].value);
    let cmp_result = unsafe {
        libc::memcmp(arg1 as *const libc::c_void, arg2 as *const libc::c_void, 16)
    };
    encode_bool(cmp_result <= 0)
}

#[no_mangle]
pub unsafe extern "C" fn uuid_gt(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg1 = decode_uuid_p(f.args[0].value);
    let arg2 = decode_uuid_p(f.args[1].value);
    let cmp_result = unsafe {
        libc::memcmp(arg1 as *const libc::c_void, arg2 as *const libc::c_void, 16)
    };
    encode_bool(cmp_result > 0)
}

#[no_mangle]
pub unsafe extern "C" fn uuid_ge(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg1 = decode_uuid_p(f.args[0].value);
    let arg2 = decode_uuid_p(f.args[1].value);
    let cmp_result = unsafe {
        libc::memcmp(arg1 as *const libc::c_void, arg2 as *const libc::c_void, 16)
    };
    encode_bool(cmp_result >= 0)
}

// ─── UUID 3-way comparison (cmp) ──

#[no_mangle]
pub unsafe extern "C" fn uuid_cmp(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg1 = decode_uuid_p(f.args[0].value);
    let arg2 = decode_uuid_p(f.args[1].value);
    let cmp_result = unsafe {
        libc::memcmp(arg1 as *const libc::c_void, arg2 as *const libc::c_void, 16)
    };
    encode_i32(cmp_result as i32)
}

// ─── UUID hash ops (hash, hash_extended) ──

#[no_mangle]
pub unsafe extern "C" fn uuid_hash(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let key = decode_uuid_p(f.args[0].value);
    encode_u32(hash_bytes_16(key))
}

#[no_mangle]
pub unsafe extern "C" fn uuid_hash_extended(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let key = decode_uuid_p(f.args[0].value);
    let seed: u64 = decode_i64(f.args[1].value) as u64;
    encode_u64(hash_bytes_16_extended(key, seed))
}
