// Generated by `rules_postgres/lean/Pg/Ir/Emit/Tid.lean`.
// DO NOT EDIT BY HAND. Regenerate via
// `rules_postgres/tools/regen/regen-tid.sh`.
//
// Source of truth: the tid comparison, clamping and hash cluster specs in
// `Pg.Ir.Emit.TidCommon`. The comparison operators delegate to
// a 3-way comparison of block number then offset number (matching real Postgres'
// ItemPointerCompare); the clamping operators return the larger/smaller pointer;
// the hash operators use Jenkins/lookup3 hashing via pg_fcinfo's
// hash_bytes_6 / hash_bytes_6_extended helpers.
//
// 10 functions = 6 comparison ops + 1 cmp op + 2 clamp ops + 2 hash ops.

#![allow(clippy::missing_safety_doc)]

use pg_fcinfo::{
    decode_i64, decode_itempointer_p,
    encode_bool, encode_i32, encode_u32, encode_u64, encode_itempointer,
    hash_bytes_6, hash_bytes_6_extended,
    FunctionCallInfoBaseData,
};

// ─── itempointer_cmp_internal helper ──

/// Mirror of Postgres' `ItemPointerCompare`: compares two 6-byte ItemPointers.
/// Returns -1, 0, or 1.
#[inline]
unsafe fn itempointer_cmp_internal(arg1: *const u8, arg2: *const u8) -> i32 {
    // BlockIdData: first 4 bytes (little-endian u32)
    let b1 = u32::from_le_bytes([
        *arg1,
        *arg1.add(1),
        *arg1.add(2),
        *arg1.add(3),
    ]);
    let b2 = u32::from_le_bytes([
        *arg2,
        *arg2.add(1),
        *arg2.add(2),
        *arg2.add(3),
    ]);
    if b1 < b2 {
        return -1;
    } else if b1 > b2 {
        return 1;
    }
    // OffsetNumber: bytes 4-5 (little-endian u16)
    let o1 = u16::from_le_bytes([*arg1.add(4), *arg1.add(5)]);
    let o2 = u16::from_le_bytes([*arg2.add(4), *arg2.add(5)]);
    if o1 < o2 {
        return -1;
    } else if o1 > o2 {
        return 1;
    }
    0
}

// ─── tid comparison ops (tideq, tidne, tidlt, tidle, tidgt, tidge) ──

#[no_mangle]
pub unsafe extern "C" fn tideq(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg1 = decode_itempointer_p(f.args[0].value);
    let arg2 = decode_itempointer_p(f.args[1].value);
    let cmp_result = itempointer_cmp_internal(arg1, arg2);
    encode_bool(cmp_result == 0)
}

#[no_mangle]
pub unsafe extern "C" fn tidne(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg1 = decode_itempointer_p(f.args[0].value);
    let arg2 = decode_itempointer_p(f.args[1].value);
    let cmp_result = itempointer_cmp_internal(arg1, arg2);
    encode_bool(cmp_result != 0)
}

#[no_mangle]
pub unsafe extern "C" fn tidlt(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg1 = decode_itempointer_p(f.args[0].value);
    let arg2 = decode_itempointer_p(f.args[1].value);
    let cmp_result = itempointer_cmp_internal(arg1, arg2);
    encode_bool(cmp_result < 0)
}

#[no_mangle]
pub unsafe extern "C" fn tidle(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg1 = decode_itempointer_p(f.args[0].value);
    let arg2 = decode_itempointer_p(f.args[1].value);
    let cmp_result = itempointer_cmp_internal(arg1, arg2);
    encode_bool(cmp_result <= 0)
}

#[no_mangle]
pub unsafe extern "C" fn tidgt(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg1 = decode_itempointer_p(f.args[0].value);
    let arg2 = decode_itempointer_p(f.args[1].value);
    let cmp_result = itempointer_cmp_internal(arg1, arg2);
    encode_bool(cmp_result > 0)
}

#[no_mangle]
pub unsafe extern "C" fn tidge(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg1 = decode_itempointer_p(f.args[0].value);
    let arg2 = decode_itempointer_p(f.args[1].value);
    let cmp_result = itempointer_cmp_internal(arg1, arg2);
    encode_bool(cmp_result >= 0)
}

// ─── tid 3-way comparison (bttidcmp) ──

#[no_mangle]
pub unsafe extern "C" fn bttidcmp(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg1 = decode_itempointer_p(f.args[0].value);
    let arg2 = decode_itempointer_p(f.args[1].value);
    let cmp_result = itempointer_cmp_internal(arg1, arg2);
    encode_i32(cmp_result)
}

// ─── tid clamping ops (tidlarger, tidsmaller) ──

#[no_mangle]
pub unsafe extern "C" fn tidlarger(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg1 = decode_itempointer_p(f.args[0].value);
    let arg2 = decode_itempointer_p(f.args[1].value);
    let cmp_result = itempointer_cmp_internal(arg1, arg2);
    let result = if cmp_result >= 0 { arg1 } else { arg2 };
    encode_itempointer(result)
}

#[no_mangle]
pub unsafe extern "C" fn tidsmaller(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg1 = decode_itempointer_p(f.args[0].value);
    let arg2 = decode_itempointer_p(f.args[1].value);
    let cmp_result = itempointer_cmp_internal(arg1, arg2);
    let result = if cmp_result <= 0 { arg1 } else { arg2 };
    encode_itempointer(result)
}

// ─── tid hash ops (hashtid, hashtidextended) ──

#[no_mangle]
pub unsafe extern "C" fn hashtid(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let key = decode_itempointer_p(f.args[0].value);
    encode_u32(hash_bytes_6(key))
}

#[no_mangle]
pub unsafe extern "C" fn hashtidextended(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let key = decode_itempointer_p(f.args[0].value);
    let seed: u64 = decode_i64(f.args[1].value) as u64;
    encode_u64(hash_bytes_6_extended(key, seed))
}
