// Generated by `rules_postgres/lean/Pg/Ir/Emit/IntCasts.lean`.
// DO NOT EDIT BY HAND. Regenerate via
// `rules_postgres/tools/regen/regen-int-casts.sh`.
//
// Integer width-cast V1 fmgr cluster: 6 functions =
// {i2toi4, i4toi2, i2toi8, i8toi2, i4toi8, i8toi4}.
//
// Widening casts (i2→i4, i2→i8, i4→i8) are pure — direct cast.
// Narrowing casts (i4→i2, i8→i2, i8→i4) check overflow bounds and
// ereport on range violation. This mirrors Postgres' ereport(ERROR, ...)
// path: a real backend catches the longjmp at the SPI/transaction
// boundary; our Rust side just sets a TLS error flag and returns 0,
// with the diff-test harness checking the (out, err) tuple round-
// trips against the vendored C oracle.

#![allow(clippy::missing_safety_doc)]

use pg_fcinfo::{
    decode_i16, decode_i32, decode_i64,
    encode_i16, encode_i32, encode_i64,
    pg_ereport_numeric_value_out_of_range, FunctionCallInfoBaseData,
};

#[no_mangle]
pub unsafe extern "C" fn i2toi4(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg = decode_i16(f.args[0].value);
    encode_i32(arg as i32)
}

#[no_mangle]
pub unsafe extern "C" fn i4toi2(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg = decode_i32(f.args[0].value);
    if arg < i16::MIN as i32 || arg > i16::MAX as i32 {
        pg_ereport_numeric_value_out_of_range();
        return 0;
    }
    encode_i16(arg as i16)
}

#[no_mangle]
pub unsafe extern "C" fn int28(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg = decode_i16(f.args[0].value);
    encode_i64(arg as i64)
}

#[no_mangle]
pub unsafe extern "C" fn int48(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg = decode_i32(f.args[0].value);
    encode_i64(arg as i64)
}

#[no_mangle]
pub unsafe extern "C" fn int82(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg = decode_i64(f.args[0].value);
    if arg < i16::MIN as i64 || arg > i16::MAX as i64 {
        pg_ereport_numeric_value_out_of_range();
        return 0;
    }
    encode_i16(arg as i16)
}

#[no_mangle]
pub unsafe extern "C" fn int84(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg = decode_i64(f.args[0].value);
    if arg < i32::MIN as i64 || arg > i32::MAX as i64 {
        pg_ereport_numeric_value_out_of_range();
        return 0;
    }
    encode_i32(arg as i32)
}
