#!/usr/bin/env bash
# check-cash-arith-grounding.sh — AST-level structural equivalence
# check for the cash-arithmetic V1 fmgr cluster.
#
# Sister to check-int-arith-grounding.sh. Pipeline:
#   Lean.Pg.Ir.Emit.CashArithC.main → /tmp/.../lean_emit.c
#   clang -ast-dump=json on Lean emit AND real PG cash.c
#   c_ast_struct_diff per function
#
# Exit 0 if all functions structurally match; 1 otherwise.

set -euo pipefail

LEAN_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../lean" && pwd)"
DIFF_BIN="$(cd "$LEAN_DIR/../../rules_lang" && pwd)/translated/pipeline/target/release/c_ast_struct_diff"

PG_INCLUDE=""
for candidate in \
    /Users/mattmarshall/Library/Caches/bazel/_bazel_mattmarshall/0fee58293a938d2caa5da4f904216d74/external/+postgres_src_extension+postgres_src/src/include \
    /Users/mattmarshall/Library/Caches/bazel/_bazel_mattmarshall/90476f1c3b5e144c1cb932d1d6a2c5b0/external/+pg+postgres_src/src/include; do
  if [ -d "$candidate" ]; then PG_INCLUDE="$candidate"; break; fi
done
if [ -z "$PG_INCLUDE" ]; then
  echo "ERROR: postgres_src include path not found in bazel cache." >&2
  exit 2
fi

# libpg_query fallback for headers generated by Postgres' build
# (fmgrprotos.h, errcodes.h) — same trick as check-int-arith-grounding.sh.
LIBPG_INCLUDE=""
for candidate in \
    /Users/mattmarshall/Library/Caches/bazel/_bazel_mattmarshall/0fee58293a938d2caa5da4f904216d74/external/+libpg_query_extension+libpg_query/src/postgres/include \
    /Users/mattmarshall/Library/Caches/bazel/_bazel_mattmarshall/90476f1c3b5e144c1cb932d1d6a2c5b0/external/+pg+libpg_query/src/postgres/include; do
  if [ -d "$candidate" ]; then LIBPG_INCLUDE="$candidate"; break; fi
done
EXTRA_INC=""
if [ -n "$LIBPG_INCLUDE" ]; then EXTRA_INC="-I $LIBPG_INCLUDE"; fi

if [ ! -x "$DIFF_BIN" ]; then
  echo "ERROR: c_ast_struct_diff binary missing: $DIFF_BIN" >&2
  exit 2
fi

WORK="$(mktemp -d -t pgir-cash-grounding.XXXXXX)"
trap 'rm -rf "$WORK"' EXIT

(
  cd "$LEAN_DIR"
  LEAN_PATH=. lean -o Pg/Ir/Types.olean                Pg/Ir/Types.lean
  LEAN_PATH=. lean -o Pg/Ir/Datum.olean                Pg/Ir/Datum.lean
  LEAN_PATH=. lean -o Pg/Ir/Cmp.olean                  Pg/Ir/Cmp.lean
  LEAN_PATH=. lean -o Pg/Ir/Emit/Common.olean          Pg/Ir/Emit/Common.lean
  LEAN_PATH=. lean -o Pg/Ir/Emit/CashArithCommon.olean Pg/Ir/Emit/CashArithCommon.lean
  LEAN_PATH=. lean -o Pg/Ir/Emit/CashArithC.olean      Pg/Ir/Emit/CashArithC.lean
)

( cd "$LEAN_DIR" && LEAN_PATH=. lean --run Pg/Ir/Emit/CashArithC.lean ) > "$WORK/lean_emit.c"
clang -Xclang -ast-dump=json -fsyntax-only -I "$PG_INCLUDE" $EXTRA_INC "$WORK/lean_emit.c" \
  2>/dev/null > "$WORK/lean.ast.json" || true
if [ ! -s "$WORK/lean.ast.json" ]; then
  echo "ERROR: clang produced empty AST for Lean emit." >&2
  exit 2
fi

# All 6 cash functions live in cash.c.
PG_SRC="$PG_INCLUDE/../backend/utils/adt/cash.c"
if [ ! -f "$PG_SRC" ]; then
  echo "ERROR: Real Postgres cash.c not found at $PG_SRC" >&2
  exit 2
fi
clang -Xclang -ast-dump=json -fsyntax-only -I "$PG_INCLUDE" $EXTRA_INC "$PG_SRC" \
  2>/dev/null > "$WORK/real_cash.ast.json" || true
if [ ! -s "$WORK/real_cash.ast.json" ]; then
  echo "ERROR: clang produced empty AST for cash.c" >&2
  exit 2
fi

pass=0; fail=0; fails=""
check() {
  local fn=$1
  if "$DIFF_BIN" --left "$WORK/real_cash.ast.json" --right "$WORK/lean.ast.json" \
       --fn-name "$fn" >/dev/null 2>&1; then
    pass=$((pass+1))
  else
    fail=$((fail+1)); fails="$fails ${fn}"
  fi
}

# All 6 functions in the v1 cluster.
check "cash_pl"
check "cash_mi"
check "cash_mul_int4"
check "cash_div_int4"
check "cashlarger"
check "cashsmaller"

total=$((pass + fail))
if [ "$fail" -eq 0 ]; then
  echo "ok: $pass / $total cash functions structurally equivalent to real Postgres."
  exit 0
else
  echo "ERROR: $fail / $total cash functions structurally differ from real Postgres:" >&2
  echo "$fails" | tr ' ' '\n' | grep -v '^$' | sed 's/^/  - /' >&2
  exit 1
fi
