#!/usr/bin/env bash
# check-int-cmp-grounding.sh — verify Lean spec ≡ real Postgres C at
# the AST level for the int comparison cluster.
#
# Companion to regen-int-cmp.sh (which handles Lean → Rust). This
# script handles Lean → C, then structurally diffs against the real
# Postgres source. A passing run proves the Lean spec captures the
# same algorithm Postgres wrote, not just its observable behavior
# on tested inputs.
#
# Pipeline:
#   Lean.Pg.Ir.Emit.IntCmpC.main → /tmp/.../lean_emit.c
#   clang -ast-dump=json on the Lean emit AND each real PG source file
#   c_ast_struct_diff per function: real C ↔ Lean-emitted C
#
# Exits 0 if every function structurally matches; 1 otherwise.
#
# CI invocation: this is run alongside `regen-int-cmp.sh --check` to
# enforce the three-way closure (Lean ↔ Rust ↔ C ↔ real PG).

set -euo pipefail

LEAN_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../lean" && pwd)"
DIFF_BIN="$(cd "$LEAN_DIR/../../rules_lang" && pwd)/translated/pipeline/target/release/c_ast_struct_diff"

# Locate postgres_src in the bazel cache. Try the two known prefixes
# (different bazel runs use different external hashes for postgres_src).
PG_INCLUDE=""
for candidate in \
    /Users/mattmarshall/Library/Caches/bazel/_bazel_mattmarshall/0fee58293a938d2caa5da4f904216d74/external/+postgres_src_extension+postgres_src/src/include \
    /Users/mattmarshall/Library/Caches/bazel/_bazel_mattmarshall/90476f1c3b5e144c1cb932d1d6a2c5b0/external/+pg+postgres_src/src/include; do
  if [ -d "$candidate" ]; then PG_INCLUDE="$candidate"; break; fi
done
if [ -z "$PG_INCLUDE" ]; then
  echo "ERROR: postgres_src include path not found in bazel cache." >&2
  echo "       Run 'bazel build @postgres_src//...' or update this script." >&2
  exit 2
fi

# char.c #includes `utils/fmgrprotos.h` (generated by Postgres' build),
# and the elog/errcodes machinery transitively pulls in `utils/errcodes.h`
# (also generated). Neither lives under postgres_src's source tree —
# they only appear in the build output. libpg_query vendors both, so
# add its include path as a fallback to resolve them. Without these,
# clang's recovery leaves `FunctionCallInfo` typedef-unresolved, which
# degrades the AST (`Datum (int)` instead of `Datum (FunctionCallInfo)`)
# and the structural diff trips on the qualType mismatch.
LIBPG_INCLUDE=""
for candidate in \
    /Users/mattmarshall/Library/Caches/bazel/_bazel_mattmarshall/0fee58293a938d2caa5da4f904216d74/external/+libpg_query_extension+libpg_query/src/postgres/include \
    /Users/mattmarshall/Library/Caches/bazel/_bazel_mattmarshall/90476f1c3b5e144c1cb932d1d6a2c5b0/external/+pg+libpg_query/src/postgres/include; do
  if [ -d "$candidate" ]; then LIBPG_INCLUDE="$candidate"; break; fi
done
EXTRA_INC=""
if [ -n "$LIBPG_INCLUDE" ]; then EXTRA_INC="-I $LIBPG_INCLUDE"; fi

if [ ! -x "$DIFF_BIN" ]; then
  echo "ERROR: c_ast_struct_diff binary missing: $DIFF_BIN" >&2
  echo "       Build it: (cd $LEAN_DIR/../../rules_lang/translated/pipeline && cargo build --release --bin c_ast_struct_diff)" >&2
  exit 2
fi

WORK="$(mktemp -d -t pgir-grounding.XXXXXX)"
trap 'rm -rf "$WORK"' EXIT

# Pre-compile Lean dependencies.
(
  cd "$LEAN_DIR"
  LEAN_PATH=. lean -o Pg/Ir/Types.olean             Pg/Ir/Types.lean
  LEAN_PATH=. lean -o Pg/Ir/Datum.olean             Pg/Ir/Datum.lean
  LEAN_PATH=. lean -o Pg/Ir/Cmp.olean               Pg/Ir/Cmp.lean
  LEAN_PATH=. lean -o Pg/Ir/Emit/Common.olean       Pg/Ir/Emit/Common.lean
  LEAN_PATH=. lean -o Pg/Ir/Emit/IntCmpC.olean      Pg/Ir/Emit/IntCmpC.lean
)

# Emit Lean's C → tmp file, dump its AST.
# clang exits non-zero on certain benign warnings (e.g.
# pg_attribute_printf macro redefinition) even though it still produces
# valid AST JSON. We tolerate non-zero exit codes here as long as the
# JSON file is non-empty and parseable; the structural diff is the real
# correctness gate downstream.
( cd "$LEAN_DIR" && LEAN_PATH=. lean --run Pg/Ir/Emit/IntCmpC.lean ) > "$WORK/lean_emit.c"
clang -Xclang -ast-dump=json -fsyntax-only -I "$PG_INCLUDE" $EXTRA_INC "$WORK/lean_emit.c" \
  2>/dev/null > "$WORK/lean.ast.json" || true
if [ ! -s "$WORK/lean.ast.json" ]; then
  echo "ERROR: clang produced empty AST for Lean emit." >&2
  exit 2
fi

# Dump each real PG source file we care about.
for srcfile in int int8 bool date cash oid pg_lsn timestamp float char; do
  PG_SRC="$PG_INCLUDE/../backend/utils/adt/${srcfile}.c"
  if [ ! -f "$PG_SRC" ]; then continue; fi
  clang -Xclang -ast-dump=json -fsyntax-only -I "$PG_INCLUDE" $EXTRA_INC "$PG_SRC" \
    2>/dev/null > "$WORK/real_${srcfile}.ast.json" || true
  if [ ! -s "$WORK/real_${srcfile}.ast.json" ]; then
    echo "WARN: clang produced empty AST for ${srcfile}.c; skipping" >&2
    rm -f "$WORK/real_${srcfile}.ast.json"
  fi
done

# Diff per function.
pass=0; fail=0; fails=""
check() {
  local src=$1 fn=$2
  if [ ! -f "$WORK/real_${src}.ast.json" ]; then return; fi
  if "$DIFF_BIN" --left "$WORK/real_${src}.ast.json" --right "$WORK/lean.ast.json" \
       --fn-name "$fn" >/dev/null 2>&1; then
    pass=$((pass+1))
  else
    fail=$((fail+1)); fails="$fails ${src}/${fn}"
  fi
}
for op in eq ne lt le gt ge; do check int int2$op;          done
for op in eq ne lt le gt ge; do check int int4$op;          done
for op in eq ne lt le gt ge; do check int8 int8$op;         done
for op in eq ne lt le gt ge; do check bool bool$op;         done
for op in eq ne lt le gt ge; do check date date_$op;        done
for op in eq ne lt le gt ge; do check cash cash_$op;        done
for op in eq ne lt le gt ge; do check oid oid$op;           done
for op in eq ne lt le gt ge; do check pg_lsn pg_lsn_$op;    done
for op in eq ne lt le gt ge; do check timestamp timestamp_$op; done
for op in eq ne lt le gt ge; do check float float4$op; done
for op in eq ne lt le gt ge; do check float float8$op; done
for op in eq ne lt le gt ge; do check char char$op; done
# Cross-type comparators: int2↔int4 live in int.c; anything involving
# int8 lives in int8.c.
for fam in int24 int42; do
  for op in eq ne lt le gt ge; do check int ${fam}$op; done
done
for fam in int28 int82 int48 int84; do
  for op in eq ne lt le gt ge; do check int8 ${fam}$op; done
done

total=$((pass + fail))
if [ "$fail" -eq 0 ]; then
  echo "ok: $pass / $total comparison functions structurally equivalent to real Postgres."
  exit 0
else
  echo "ERROR: $fail / $total functions structurally differ from real Postgres:" >&2
  echo "$fails" | tr ' ' '\n' | grep -v '^$' | sed 's/^/  - /' >&2
  exit 1
fi
