// Generated by `rules_postgres/lean/Pg/Ir/Emit/FloatArith.lean`.
// DO NOT EDIT BY HAND. Regenerate via
// `rules_postgres/tools/regen/regen-float-arith.sh`.
//
// Float arithmetic V1 fmgr cluster: 8 functions = {pl, mi, mul, div} × {float4, float8}.
// Each body decodes two arguments, applies IEEE-754 arithmetic, and checks
// for overflow/underflow conditions matching Postgres' float.h helpers:
//   - pl/mi: check overflow (result inf but neither input inf)
//   - mul: check overflow AND underflow (result 0 but neither input 0)
//   - div: divide-by-zero first, then overflow/underflow checks

#![allow(clippy::missing_safety_doc)]

use pg_fcinfo::{
    decode_f32, decode_f64,
    encode_f32, encode_f64,
    pg_ereport_numeric_value_out_of_range,
    pg_ereport_division_by_zero,
    FunctionCallInfoBaseData,
};

#[no_mangle]
pub unsafe extern "C" fn float4pl(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg1 = decode_f32(f.args[0].value);
    let arg2 = decode_f32(f.args[1].value);
    let result: f32 = arg1 + arg2;
    if result.is_infinite() && !arg1.is_infinite() && !arg2.is_infinite() {
        pg_ereport_numeric_value_out_of_range();
        return 0;
    }
    encode_f32(result)
}

#[no_mangle]
pub unsafe extern "C" fn float8pl(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg1 = decode_f64(f.args[0].value);
    let arg2 = decode_f64(f.args[1].value);
    let result: f64 = arg1 + arg2;
    if result.is_infinite() && !arg1.is_infinite() && !arg2.is_infinite() {
        pg_ereport_numeric_value_out_of_range();
        return 0;
    }
    encode_f64(result)
}

#[no_mangle]
pub unsafe extern "C" fn float4mi(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg1 = decode_f32(f.args[0].value);
    let arg2 = decode_f32(f.args[1].value);
    let result: f32 = arg1 - arg2;
    if result.is_infinite() && !arg1.is_infinite() && !arg2.is_infinite() {
        pg_ereport_numeric_value_out_of_range();
        return 0;
    }
    encode_f32(result)
}

#[no_mangle]
pub unsafe extern "C" fn float8mi(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg1 = decode_f64(f.args[0].value);
    let arg2 = decode_f64(f.args[1].value);
    let result: f64 = arg1 - arg2;
    if result.is_infinite() && !arg1.is_infinite() && !arg2.is_infinite() {
        pg_ereport_numeric_value_out_of_range();
        return 0;
    }
    encode_f64(result)
}

#[no_mangle]
pub unsafe extern "C" fn float4mul(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg1 = decode_f32(f.args[0].value);
    let arg2 = decode_f32(f.args[1].value);
    let result: f32 = arg1 * arg2;
    if result.is_infinite() && !arg1.is_infinite() && !arg2.is_infinite() {
        pg_ereport_numeric_value_out_of_range();
        return 0;
    }
    if result == 0.0 && arg1 != 0.0 && arg2 != 0.0 {
        pg_ereport_numeric_value_out_of_range();
        return 0;
    }
    encode_f32(result)
}

#[no_mangle]
pub unsafe extern "C" fn float8mul(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg1 = decode_f64(f.args[0].value);
    let arg2 = decode_f64(f.args[1].value);
    let result: f64 = arg1 * arg2;
    if result.is_infinite() && !arg1.is_infinite() && !arg2.is_infinite() {
        pg_ereport_numeric_value_out_of_range();
        return 0;
    }
    if result == 0.0 && arg1 != 0.0 && arg2 != 0.0 {
        pg_ereport_numeric_value_out_of_range();
        return 0;
    }
    encode_f64(result)
}

#[no_mangle]
pub unsafe extern "C" fn float4div(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg1 = decode_f32(f.args[0].value);
    let arg2 = decode_f32(f.args[1].value);
    if arg2 == 0.0 && !arg1.is_nan() {
        pg_ereport_division_by_zero();
        return 0;
    }
    let result: f32 = arg1 / arg2;
    if result.is_infinite() && !arg1.is_infinite() {
        pg_ereport_numeric_value_out_of_range();
        return 0;
    }
    if result == 0.0 && arg1 != 0.0 && !arg2.is_infinite() {
        pg_ereport_numeric_value_out_of_range();
        return 0;
    }
    encode_f32(result)
}

#[no_mangle]
pub unsafe extern "C" fn float8div(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg1 = decode_f64(f.args[0].value);
    let arg2 = decode_f64(f.args[1].value);
    if arg2 == 0.0 && !arg1.is_nan() {
        pg_ereport_division_by_zero();
        return 0;
    }
    let result: f64 = arg1 / arg2;
    if result.is_infinite() && !arg1.is_infinite() {
        pg_ereport_numeric_value_out_of_range();
        return 0;
    }
    if result == 0.0 && arg1 != 0.0 && !arg2.is_infinite() {
        pg_ereport_numeric_value_out_of_range();
        return 0;
    }
    encode_f64(result)
}
