// Generated by `rules_postgres/lean/Pg/Ir/Emit/IntArith.lean`.
// DO NOT EDIT BY HAND. Regenerate via
// `rules_postgres/tools/regen/regen-int-arith.sh`.
//
// Integer-arithmetic V1 fmgr cluster: 21 functions =
// {pl, mi, mul} × {int2, int4, int8} (same-type, 9 fns) +
// {pl, mi, mul} × {int24, int42, int48, int84, int28, int82}
// (cross-type, 12 fns).
//
// Each body decodes both operands, calls the matching
// pg_<op>_s<W>_overflow primitive (W = result-type width), and
// on overflow signals via pg_ereport_numeric_value_out_of_range()
// + returning Datum 0. This mirrors Postgres' ereport(ERROR, ...)
// path: a real backend catches the longjmp at the SPI/transaction
// boundary; our Rust side just sets a TLS error flag and returns 0,
// with the diff-test harness checking the (out, err) tuple round-
// trips against the vendored C oracle.

#![allow(clippy::missing_safety_doc)]

use pg_fcinfo::{
    decode_i16, decode_i32, decode_i64,
    encode_i16, encode_i32, encode_i64,
    pg_add_s16_overflow, pg_add_s32_overflow, pg_add_s64_overflow,
    pg_sub_s16_overflow, pg_sub_s32_overflow, pg_sub_s64_overflow,
    pg_mul_s16_overflow, pg_mul_s32_overflow, pg_mul_s64_overflow,
    pg_ereport_numeric_value_out_of_range, FunctionCallInfoBaseData,
};

#[no_mangle]
pub unsafe extern "C" fn int2pl(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg1 = decode_i16(f.args[0].value);
    let arg2 = decode_i16(f.args[1].value);
    let mut result: i16 = 0;
    if pg_add_s16_overflow(arg1, arg2, &mut result) {
        pg_ereport_numeric_value_out_of_range();
        return 0;
    }
    encode_i16(result)
}

#[no_mangle]
pub unsafe extern "C" fn int2mi(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg1 = decode_i16(f.args[0].value);
    let arg2 = decode_i16(f.args[1].value);
    let mut result: i16 = 0;
    if pg_sub_s16_overflow(arg1, arg2, &mut result) {
        pg_ereport_numeric_value_out_of_range();
        return 0;
    }
    encode_i16(result)
}

#[no_mangle]
pub unsafe extern "C" fn int2mul(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg1 = decode_i16(f.args[0].value);
    let arg2 = decode_i16(f.args[1].value);
    let mut result: i16 = 0;
    if pg_mul_s16_overflow(arg1, arg2, &mut result) {
        pg_ereport_numeric_value_out_of_range();
        return 0;
    }
    encode_i16(result)
}

#[no_mangle]
pub unsafe extern "C" fn int4pl(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg1 = decode_i32(f.args[0].value);
    let arg2 = decode_i32(f.args[1].value);
    let mut result: i32 = 0;
    if pg_add_s32_overflow(arg1, arg2, &mut result) {
        pg_ereport_numeric_value_out_of_range();
        return 0;
    }
    encode_i32(result)
}

#[no_mangle]
pub unsafe extern "C" fn int4mi(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg1 = decode_i32(f.args[0].value);
    let arg2 = decode_i32(f.args[1].value);
    let mut result: i32 = 0;
    if pg_sub_s32_overflow(arg1, arg2, &mut result) {
        pg_ereport_numeric_value_out_of_range();
        return 0;
    }
    encode_i32(result)
}

#[no_mangle]
pub unsafe extern "C" fn int4mul(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg1 = decode_i32(f.args[0].value);
    let arg2 = decode_i32(f.args[1].value);
    let mut result: i32 = 0;
    if pg_mul_s32_overflow(arg1, arg2, &mut result) {
        pg_ereport_numeric_value_out_of_range();
        return 0;
    }
    encode_i32(result)
}

#[no_mangle]
pub unsafe extern "C" fn int8pl(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg1 = decode_i64(f.args[0].value);
    let arg2 = decode_i64(f.args[1].value);
    let mut result: i64 = 0;
    if pg_add_s64_overflow(arg1, arg2, &mut result) {
        pg_ereport_numeric_value_out_of_range();
        return 0;
    }
    encode_i64(result)
}

#[no_mangle]
pub unsafe extern "C" fn int8mi(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg1 = decode_i64(f.args[0].value);
    let arg2 = decode_i64(f.args[1].value);
    let mut result: i64 = 0;
    if pg_sub_s64_overflow(arg1, arg2, &mut result) {
        pg_ereport_numeric_value_out_of_range();
        return 0;
    }
    encode_i64(result)
}

#[no_mangle]
pub unsafe extern "C" fn int8mul(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg1 = decode_i64(f.args[0].value);
    let arg2 = decode_i64(f.args[1].value);
    let mut result: i64 = 0;
    if pg_mul_s64_overflow(arg1, arg2, &mut result) {
        pg_ereport_numeric_value_out_of_range();
        return 0;
    }
    encode_i64(result)
}

#[no_mangle]
pub unsafe extern "C" fn int24pl(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg1 = decode_i16(f.args[0].value);
    let arg2 = decode_i32(f.args[1].value);
    let mut result: i32 = 0;
    if pg_add_s32_overflow(arg1 as i32, arg2, &mut result) {
        pg_ereport_numeric_value_out_of_range();
        return 0;
    }
    encode_i32(result)
}

#[no_mangle]
pub unsafe extern "C" fn int24mi(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg1 = decode_i16(f.args[0].value);
    let arg2 = decode_i32(f.args[1].value);
    let mut result: i32 = 0;
    if pg_sub_s32_overflow(arg1 as i32, arg2, &mut result) {
        pg_ereport_numeric_value_out_of_range();
        return 0;
    }
    encode_i32(result)
}

#[no_mangle]
pub unsafe extern "C" fn int24mul(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg1 = decode_i16(f.args[0].value);
    let arg2 = decode_i32(f.args[1].value);
    let mut result: i32 = 0;
    if pg_mul_s32_overflow(arg1 as i32, arg2, &mut result) {
        pg_ereport_numeric_value_out_of_range();
        return 0;
    }
    encode_i32(result)
}

#[no_mangle]
pub unsafe extern "C" fn int42pl(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg1 = decode_i32(f.args[0].value);
    let arg2 = decode_i16(f.args[1].value);
    let mut result: i32 = 0;
    if pg_add_s32_overflow(arg1, arg2 as i32, &mut result) {
        pg_ereport_numeric_value_out_of_range();
        return 0;
    }
    encode_i32(result)
}

#[no_mangle]
pub unsafe extern "C" fn int42mi(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg1 = decode_i32(f.args[0].value);
    let arg2 = decode_i16(f.args[1].value);
    let mut result: i32 = 0;
    if pg_sub_s32_overflow(arg1, arg2 as i32, &mut result) {
        pg_ereport_numeric_value_out_of_range();
        return 0;
    }
    encode_i32(result)
}

#[no_mangle]
pub unsafe extern "C" fn int42mul(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg1 = decode_i32(f.args[0].value);
    let arg2 = decode_i16(f.args[1].value);
    let mut result: i32 = 0;
    if pg_mul_s32_overflow(arg1, arg2 as i32, &mut result) {
        pg_ereport_numeric_value_out_of_range();
        return 0;
    }
    encode_i32(result)
}

#[no_mangle]
pub unsafe extern "C" fn int48pl(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg1 = decode_i32(f.args[0].value);
    let arg2 = decode_i64(f.args[1].value);
    let mut result: i64 = 0;
    if pg_add_s64_overflow(arg1 as i64, arg2, &mut result) {
        pg_ereport_numeric_value_out_of_range();
        return 0;
    }
    encode_i64(result)
}

#[no_mangle]
pub unsafe extern "C" fn int48mi(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg1 = decode_i32(f.args[0].value);
    let arg2 = decode_i64(f.args[1].value);
    let mut result: i64 = 0;
    if pg_sub_s64_overflow(arg1 as i64, arg2, &mut result) {
        pg_ereport_numeric_value_out_of_range();
        return 0;
    }
    encode_i64(result)
}

#[no_mangle]
pub unsafe extern "C" fn int48mul(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg1 = decode_i32(f.args[0].value);
    let arg2 = decode_i64(f.args[1].value);
    let mut result: i64 = 0;
    if pg_mul_s64_overflow(arg1 as i64, arg2, &mut result) {
        pg_ereport_numeric_value_out_of_range();
        return 0;
    }
    encode_i64(result)
}

#[no_mangle]
pub unsafe extern "C" fn int84pl(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg1 = decode_i64(f.args[0].value);
    let arg2 = decode_i32(f.args[1].value);
    let mut result: i64 = 0;
    if pg_add_s64_overflow(arg1, arg2 as i64, &mut result) {
        pg_ereport_numeric_value_out_of_range();
        return 0;
    }
    encode_i64(result)
}

#[no_mangle]
pub unsafe extern "C" fn int84mi(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg1 = decode_i64(f.args[0].value);
    let arg2 = decode_i32(f.args[1].value);
    let mut result: i64 = 0;
    if pg_sub_s64_overflow(arg1, arg2 as i64, &mut result) {
        pg_ereport_numeric_value_out_of_range();
        return 0;
    }
    encode_i64(result)
}

#[no_mangle]
pub unsafe extern "C" fn int84mul(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg1 = decode_i64(f.args[0].value);
    let arg2 = decode_i32(f.args[1].value);
    let mut result: i64 = 0;
    if pg_mul_s64_overflow(arg1, arg2 as i64, &mut result) {
        pg_ereport_numeric_value_out_of_range();
        return 0;
    }
    encode_i64(result)
}

#[no_mangle]
pub unsafe extern "C" fn int28pl(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg1 = decode_i16(f.args[0].value);
    let arg2 = decode_i64(f.args[1].value);
    let mut result: i64 = 0;
    if pg_add_s64_overflow(arg1 as i64, arg2, &mut result) {
        pg_ereport_numeric_value_out_of_range();
        return 0;
    }
    encode_i64(result)
}

#[no_mangle]
pub unsafe extern "C" fn int28mi(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg1 = decode_i16(f.args[0].value);
    let arg2 = decode_i64(f.args[1].value);
    let mut result: i64 = 0;
    if pg_sub_s64_overflow(arg1 as i64, arg2, &mut result) {
        pg_ereport_numeric_value_out_of_range();
        return 0;
    }
    encode_i64(result)
}

#[no_mangle]
pub unsafe extern "C" fn int28mul(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg1 = decode_i16(f.args[0].value);
    let arg2 = decode_i64(f.args[1].value);
    let mut result: i64 = 0;
    if pg_mul_s64_overflow(arg1 as i64, arg2, &mut result) {
        pg_ereport_numeric_value_out_of_range();
        return 0;
    }
    encode_i64(result)
}

#[no_mangle]
pub unsafe extern "C" fn int82pl(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg1 = decode_i64(f.args[0].value);
    let arg2 = decode_i16(f.args[1].value);
    let mut result: i64 = 0;
    if pg_add_s64_overflow(arg1, arg2 as i64, &mut result) {
        pg_ereport_numeric_value_out_of_range();
        return 0;
    }
    encode_i64(result)
}

#[no_mangle]
pub unsafe extern "C" fn int82mi(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg1 = decode_i64(f.args[0].value);
    let arg2 = decode_i16(f.args[1].value);
    let mut result: i64 = 0;
    if pg_sub_s64_overflow(arg1, arg2 as i64, &mut result) {
        pg_ereport_numeric_value_out_of_range();
        return 0;
    }
    encode_i64(result)
}

#[no_mangle]
pub unsafe extern "C" fn int82mul(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg1 = decode_i64(f.args[0].value);
    let arg2 = decode_i16(f.args[1].value);
    let mut result: i64 = 0;
    if pg_mul_s64_overflow(arg1, arg2 as i64, &mut result) {
        pg_ereport_numeric_value_out_of_range();
        return 0;
    }
    encode_i64(result)
}
