// Generated by `rules_postgres/lean/Pg/Ir/Emit/IntCmp.lean`.
// DO NOT EDIT BY HAND. Regenerate via
// `rules_postgres/tools/regen/regen-int-cmp.sh`.
//
// Source of truth: the polymorphic comparison primitives in
// `Pg.Ir.Cmp` instantiated at the Postgres type families in
// `Pg.Ir.Types`. Each emitted function matches the corresponding
// cmp* spec theorem in Pg.Ir.Cmp (see `cmpEq_spec` etc.). The C
// side is gated by the diff-test in tests/diff_int4_cmp.rs (~98K
// cases passing against real Postgres 17.6).
//
// 48 functions = 8 type families × 6 comparison operations.

#![allow(clippy::missing_safety_doc)]

use pg_fcinfo::{
    decode_bool, decode_f32, decode_f64, decode_i8,
    decode_i16, decode_i32, decode_i64, decode_u32, decode_u64,
    encode_bool, FunctionCallInfoBaseData,
};

// ─── int2 family (decoder: decode_i16) ──

#[no_mangle]
pub unsafe extern "C" fn int2eq(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_i16(f.args[0].value);
    let b = decode_i16(f.args[1].value);
    encode_bool(a == b)
}

#[no_mangle]
pub unsafe extern "C" fn int2ne(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_i16(f.args[0].value);
    let b = decode_i16(f.args[1].value);
    encode_bool(a != b)
}

#[no_mangle]
pub unsafe extern "C" fn int2lt(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_i16(f.args[0].value);
    let b = decode_i16(f.args[1].value);
    encode_bool(a < b)
}

#[no_mangle]
pub unsafe extern "C" fn int2le(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_i16(f.args[0].value);
    let b = decode_i16(f.args[1].value);
    encode_bool(a <= b)
}

#[no_mangle]
pub unsafe extern "C" fn int2gt(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_i16(f.args[0].value);
    let b = decode_i16(f.args[1].value);
    encode_bool(a > b)
}

#[no_mangle]
pub unsafe extern "C" fn int2ge(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_i16(f.args[0].value);
    let b = decode_i16(f.args[1].value);
    encode_bool(a >= b)
}

// ─── int4 family (decoder: decode_i32) ──

#[no_mangle]
pub unsafe extern "C" fn int4eq(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_i32(f.args[0].value);
    let b = decode_i32(f.args[1].value);
    encode_bool(a == b)
}

#[no_mangle]
pub unsafe extern "C" fn int4ne(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_i32(f.args[0].value);
    let b = decode_i32(f.args[1].value);
    encode_bool(a != b)
}

#[no_mangle]
pub unsafe extern "C" fn int4lt(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_i32(f.args[0].value);
    let b = decode_i32(f.args[1].value);
    encode_bool(a < b)
}

#[no_mangle]
pub unsafe extern "C" fn int4le(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_i32(f.args[0].value);
    let b = decode_i32(f.args[1].value);
    encode_bool(a <= b)
}

#[no_mangle]
pub unsafe extern "C" fn int4gt(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_i32(f.args[0].value);
    let b = decode_i32(f.args[1].value);
    encode_bool(a > b)
}

#[no_mangle]
pub unsafe extern "C" fn int4ge(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_i32(f.args[0].value);
    let b = decode_i32(f.args[1].value);
    encode_bool(a >= b)
}

// ─── int8 family (decoder: decode_i64) ──

#[no_mangle]
pub unsafe extern "C" fn int8eq(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_i64(f.args[0].value);
    let b = decode_i64(f.args[1].value);
    encode_bool(a == b)
}

#[no_mangle]
pub unsafe extern "C" fn int8ne(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_i64(f.args[0].value);
    let b = decode_i64(f.args[1].value);
    encode_bool(a != b)
}

#[no_mangle]
pub unsafe extern "C" fn int8lt(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_i64(f.args[0].value);
    let b = decode_i64(f.args[1].value);
    encode_bool(a < b)
}

#[no_mangle]
pub unsafe extern "C" fn int8le(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_i64(f.args[0].value);
    let b = decode_i64(f.args[1].value);
    encode_bool(a <= b)
}

#[no_mangle]
pub unsafe extern "C" fn int8gt(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_i64(f.args[0].value);
    let b = decode_i64(f.args[1].value);
    encode_bool(a > b)
}

#[no_mangle]
pub unsafe extern "C" fn int8ge(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_i64(f.args[0].value);
    let b = decode_i64(f.args[1].value);
    encode_bool(a >= b)
}

// ─── date_ family (decoder: decode_i32) ──

#[no_mangle]
pub unsafe extern "C" fn date_eq(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_i32(f.args[0].value);
    let b = decode_i32(f.args[1].value);
    encode_bool(a == b)
}

#[no_mangle]
pub unsafe extern "C" fn date_ne(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_i32(f.args[0].value);
    let b = decode_i32(f.args[1].value);
    encode_bool(a != b)
}

#[no_mangle]
pub unsafe extern "C" fn date_lt(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_i32(f.args[0].value);
    let b = decode_i32(f.args[1].value);
    encode_bool(a < b)
}

#[no_mangle]
pub unsafe extern "C" fn date_le(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_i32(f.args[0].value);
    let b = decode_i32(f.args[1].value);
    encode_bool(a <= b)
}

#[no_mangle]
pub unsafe extern "C" fn date_gt(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_i32(f.args[0].value);
    let b = decode_i32(f.args[1].value);
    encode_bool(a > b)
}

#[no_mangle]
pub unsafe extern "C" fn date_ge(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_i32(f.args[0].value);
    let b = decode_i32(f.args[1].value);
    encode_bool(a >= b)
}

// ─── timestamp_ family (decoder: decode_i64) ──

#[no_mangle]
pub unsafe extern "C" fn timestamp_eq(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_i64(f.args[0].value);
    let b = decode_i64(f.args[1].value);
    encode_bool(pg_fcinfo::timestamp_cmp_internal(a, b) == 0)
}

#[no_mangle]
pub unsafe extern "C" fn timestamp_ne(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_i64(f.args[0].value);
    let b = decode_i64(f.args[1].value);
    encode_bool(pg_fcinfo::timestamp_cmp_internal(a, b) != 0)
}

#[no_mangle]
pub unsafe extern "C" fn timestamp_lt(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_i64(f.args[0].value);
    let b = decode_i64(f.args[1].value);
    encode_bool(pg_fcinfo::timestamp_cmp_internal(a, b) < 0)
}

#[no_mangle]
pub unsafe extern "C" fn timestamp_le(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_i64(f.args[0].value);
    let b = decode_i64(f.args[1].value);
    encode_bool(pg_fcinfo::timestamp_cmp_internal(a, b) <= 0)
}

#[no_mangle]
pub unsafe extern "C" fn timestamp_gt(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_i64(f.args[0].value);
    let b = decode_i64(f.args[1].value);
    encode_bool(pg_fcinfo::timestamp_cmp_internal(a, b) > 0)
}

#[no_mangle]
pub unsafe extern "C" fn timestamp_ge(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_i64(f.args[0].value);
    let b = decode_i64(f.args[1].value);
    encode_bool(pg_fcinfo::timestamp_cmp_internal(a, b) >= 0)
}

// ─── cash_ family (decoder: decode_i64) ──

#[no_mangle]
pub unsafe extern "C" fn cash_eq(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_i64(f.args[0].value);
    let b = decode_i64(f.args[1].value);
    encode_bool(a == b)
}

#[no_mangle]
pub unsafe extern "C" fn cash_ne(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_i64(f.args[0].value);
    let b = decode_i64(f.args[1].value);
    encode_bool(a != b)
}

#[no_mangle]
pub unsafe extern "C" fn cash_lt(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_i64(f.args[0].value);
    let b = decode_i64(f.args[1].value);
    encode_bool(a < b)
}

#[no_mangle]
pub unsafe extern "C" fn cash_le(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_i64(f.args[0].value);
    let b = decode_i64(f.args[1].value);
    encode_bool(a <= b)
}

#[no_mangle]
pub unsafe extern "C" fn cash_gt(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_i64(f.args[0].value);
    let b = decode_i64(f.args[1].value);
    encode_bool(a > b)
}

#[no_mangle]
pub unsafe extern "C" fn cash_ge(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_i64(f.args[0].value);
    let b = decode_i64(f.args[1].value);
    encode_bool(a >= b)
}

// ─── pg_lsn_ family (decoder: decode_u64) ──

#[no_mangle]
pub unsafe extern "C" fn pg_lsn_eq(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_u64(f.args[0].value);
    let b = decode_u64(f.args[1].value);
    encode_bool(a == b)
}

#[no_mangle]
pub unsafe extern "C" fn pg_lsn_ne(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_u64(f.args[0].value);
    let b = decode_u64(f.args[1].value);
    encode_bool(a != b)
}

#[no_mangle]
pub unsafe extern "C" fn pg_lsn_lt(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_u64(f.args[0].value);
    let b = decode_u64(f.args[1].value);
    encode_bool(a < b)
}

#[no_mangle]
pub unsafe extern "C" fn pg_lsn_le(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_u64(f.args[0].value);
    let b = decode_u64(f.args[1].value);
    encode_bool(a <= b)
}

#[no_mangle]
pub unsafe extern "C" fn pg_lsn_gt(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_u64(f.args[0].value);
    let b = decode_u64(f.args[1].value);
    encode_bool(a > b)
}

#[no_mangle]
pub unsafe extern "C" fn pg_lsn_ge(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_u64(f.args[0].value);
    let b = decode_u64(f.args[1].value);
    encode_bool(a >= b)
}

// ─── oid family (decoder: decode_u32) ──

#[no_mangle]
pub unsafe extern "C" fn oideq(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_u32(f.args[0].value);
    let b = decode_u32(f.args[1].value);
    encode_bool(a == b)
}

#[no_mangle]
pub unsafe extern "C" fn oidne(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_u32(f.args[0].value);
    let b = decode_u32(f.args[1].value);
    encode_bool(a != b)
}

#[no_mangle]
pub unsafe extern "C" fn oidlt(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_u32(f.args[0].value);
    let b = decode_u32(f.args[1].value);
    encode_bool(a < b)
}

#[no_mangle]
pub unsafe extern "C" fn oidle(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_u32(f.args[0].value);
    let b = decode_u32(f.args[1].value);
    encode_bool(a <= b)
}

#[no_mangle]
pub unsafe extern "C" fn oidgt(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_u32(f.args[0].value);
    let b = decode_u32(f.args[1].value);
    encode_bool(a > b)
}

#[no_mangle]
pub unsafe extern "C" fn oidge(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_u32(f.args[0].value);
    let b = decode_u32(f.args[1].value);
    encode_bool(a >= b)
}

// ─── bool family (decoder: decode_bool) ──

#[no_mangle]
pub unsafe extern "C" fn booleq(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_bool(f.args[0].value);
    let b = decode_bool(f.args[1].value);
    encode_bool(a == b)
}

#[no_mangle]
pub unsafe extern "C" fn boolne(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_bool(f.args[0].value);
    let b = decode_bool(f.args[1].value);
    encode_bool(a != b)
}

#[no_mangle]
pub unsafe extern "C" fn boollt(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_bool(f.args[0].value);
    let b = decode_bool(f.args[1].value);
    encode_bool(a < b)
}

#[no_mangle]
pub unsafe extern "C" fn boolle(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_bool(f.args[0].value);
    let b = decode_bool(f.args[1].value);
    encode_bool(a <= b)
}

#[no_mangle]
pub unsafe extern "C" fn boolgt(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_bool(f.args[0].value);
    let b = decode_bool(f.args[1].value);
    encode_bool(a > b)
}

#[no_mangle]
pub unsafe extern "C" fn boolge(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_bool(f.args[0].value);
    let b = decode_bool(f.args[1].value);
    encode_bool(a >= b)
}

// ─── float4 family (decoder: decode_f32) ──

#[no_mangle]
pub unsafe extern "C" fn float4eq(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_f32(f.args[0].value);
    let b = decode_f32(f.args[1].value);
    encode_bool(pg_fcinfo::pgcmp_eq_f32(a, b))
}

#[no_mangle]
pub unsafe extern "C" fn float4ne(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_f32(f.args[0].value);
    let b = decode_f32(f.args[1].value);
    encode_bool(pg_fcinfo::pgcmp_ne_f32(a, b))
}

#[no_mangle]
pub unsafe extern "C" fn float4lt(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_f32(f.args[0].value);
    let b = decode_f32(f.args[1].value);
    encode_bool(pg_fcinfo::pgcmp_lt_f32(a, b))
}

#[no_mangle]
pub unsafe extern "C" fn float4le(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_f32(f.args[0].value);
    let b = decode_f32(f.args[1].value);
    encode_bool(pg_fcinfo::pgcmp_le_f32(a, b))
}

#[no_mangle]
pub unsafe extern "C" fn float4gt(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_f32(f.args[0].value);
    let b = decode_f32(f.args[1].value);
    encode_bool(pg_fcinfo::pgcmp_gt_f32(a, b))
}

#[no_mangle]
pub unsafe extern "C" fn float4ge(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_f32(f.args[0].value);
    let b = decode_f32(f.args[1].value);
    encode_bool(pg_fcinfo::pgcmp_ge_f32(a, b))
}

// ─── float8 family (decoder: decode_f64) ──

#[no_mangle]
pub unsafe extern "C" fn float8eq(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_f64(f.args[0].value);
    let b = decode_f64(f.args[1].value);
    encode_bool(pg_fcinfo::pgcmp_eq_f64(a, b))
}

#[no_mangle]
pub unsafe extern "C" fn float8ne(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_f64(f.args[0].value);
    let b = decode_f64(f.args[1].value);
    encode_bool(pg_fcinfo::pgcmp_ne_f64(a, b))
}

#[no_mangle]
pub unsafe extern "C" fn float8lt(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_f64(f.args[0].value);
    let b = decode_f64(f.args[1].value);
    encode_bool(pg_fcinfo::pgcmp_lt_f64(a, b))
}

#[no_mangle]
pub unsafe extern "C" fn float8le(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_f64(f.args[0].value);
    let b = decode_f64(f.args[1].value);
    encode_bool(pg_fcinfo::pgcmp_le_f64(a, b))
}

#[no_mangle]
pub unsafe extern "C" fn float8gt(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_f64(f.args[0].value);
    let b = decode_f64(f.args[1].value);
    encode_bool(pg_fcinfo::pgcmp_gt_f64(a, b))
}

#[no_mangle]
pub unsafe extern "C" fn float8ge(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_f64(f.args[0].value);
    let b = decode_f64(f.args[1].value);
    encode_bool(pg_fcinfo::pgcmp_ge_f64(a, b))
}

// ─── char family (decoder: decode_i8) ──

#[no_mangle]
pub unsafe extern "C" fn chareq(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_i8(f.args[0].value);
    let b = decode_i8(f.args[1].value);
    encode_bool(a == b)
}

#[no_mangle]
pub unsafe extern "C" fn charne(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_i8(f.args[0].value);
    let b = decode_i8(f.args[1].value);
    encode_bool(a != b)
}

#[no_mangle]
pub unsafe extern "C" fn charlt(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_i8(f.args[0].value);
    let b = decode_i8(f.args[1].value);
    encode_bool((a as u8) < (b as u8))
}

#[no_mangle]
pub unsafe extern "C" fn charle(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_i8(f.args[0].value);
    let b = decode_i8(f.args[1].value);
    encode_bool((a as u8) <= (b as u8))
}

#[no_mangle]
pub unsafe extern "C" fn chargt(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_i8(f.args[0].value);
    let b = decode_i8(f.args[1].value);
    encode_bool((a as u8) > (b as u8))
}

#[no_mangle]
pub unsafe extern "C" fn charge(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_i8(f.args[0].value);
    let b = decode_i8(f.args[1].value);
    encode_bool((a as u8) >= (b as u8))
}

// ─── int24 family (decoder: decode_i16) ──

#[no_mangle]
pub unsafe extern "C" fn int24eq(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_i16(f.args[0].value);
    let b = decode_i32(f.args[1].value);
    encode_bool((a as i32) == (b as i32))
}

#[no_mangle]
pub unsafe extern "C" fn int24ne(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_i16(f.args[0].value);
    let b = decode_i32(f.args[1].value);
    encode_bool((a as i32) != (b as i32))
}

#[no_mangle]
pub unsafe extern "C" fn int24lt(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_i16(f.args[0].value);
    let b = decode_i32(f.args[1].value);
    encode_bool((a as i32) < (b as i32))
}

#[no_mangle]
pub unsafe extern "C" fn int24le(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_i16(f.args[0].value);
    let b = decode_i32(f.args[1].value);
    encode_bool((a as i32) <= (b as i32))
}

#[no_mangle]
pub unsafe extern "C" fn int24gt(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_i16(f.args[0].value);
    let b = decode_i32(f.args[1].value);
    encode_bool((a as i32) > (b as i32))
}

#[no_mangle]
pub unsafe extern "C" fn int24ge(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_i16(f.args[0].value);
    let b = decode_i32(f.args[1].value);
    encode_bool((a as i32) >= (b as i32))
}

// ─── int42 family (decoder: decode_i32) ──

#[no_mangle]
pub unsafe extern "C" fn int42eq(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_i32(f.args[0].value);
    let b = decode_i16(f.args[1].value);
    encode_bool((a as i32) == (b as i32))
}

#[no_mangle]
pub unsafe extern "C" fn int42ne(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_i32(f.args[0].value);
    let b = decode_i16(f.args[1].value);
    encode_bool((a as i32) != (b as i32))
}

#[no_mangle]
pub unsafe extern "C" fn int42lt(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_i32(f.args[0].value);
    let b = decode_i16(f.args[1].value);
    encode_bool((a as i32) < (b as i32))
}

#[no_mangle]
pub unsafe extern "C" fn int42le(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_i32(f.args[0].value);
    let b = decode_i16(f.args[1].value);
    encode_bool((a as i32) <= (b as i32))
}

#[no_mangle]
pub unsafe extern "C" fn int42gt(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_i32(f.args[0].value);
    let b = decode_i16(f.args[1].value);
    encode_bool((a as i32) > (b as i32))
}

#[no_mangle]
pub unsafe extern "C" fn int42ge(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_i32(f.args[0].value);
    let b = decode_i16(f.args[1].value);
    encode_bool((a as i32) >= (b as i32))
}

// ─── int28 family (decoder: decode_i16) ──

#[no_mangle]
pub unsafe extern "C" fn int28eq(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_i16(f.args[0].value);
    let b = decode_i64(f.args[1].value);
    encode_bool((a as i64) == (b as i64))
}

#[no_mangle]
pub unsafe extern "C" fn int28ne(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_i16(f.args[0].value);
    let b = decode_i64(f.args[1].value);
    encode_bool((a as i64) != (b as i64))
}

#[no_mangle]
pub unsafe extern "C" fn int28lt(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_i16(f.args[0].value);
    let b = decode_i64(f.args[1].value);
    encode_bool((a as i64) < (b as i64))
}

#[no_mangle]
pub unsafe extern "C" fn int28le(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_i16(f.args[0].value);
    let b = decode_i64(f.args[1].value);
    encode_bool((a as i64) <= (b as i64))
}

#[no_mangle]
pub unsafe extern "C" fn int28gt(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_i16(f.args[0].value);
    let b = decode_i64(f.args[1].value);
    encode_bool((a as i64) > (b as i64))
}

#[no_mangle]
pub unsafe extern "C" fn int28ge(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_i16(f.args[0].value);
    let b = decode_i64(f.args[1].value);
    encode_bool((a as i64) >= (b as i64))
}

// ─── int82 family (decoder: decode_i64) ──

#[no_mangle]
pub unsafe extern "C" fn int82eq(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_i64(f.args[0].value);
    let b = decode_i16(f.args[1].value);
    encode_bool((a as i64) == (b as i64))
}

#[no_mangle]
pub unsafe extern "C" fn int82ne(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_i64(f.args[0].value);
    let b = decode_i16(f.args[1].value);
    encode_bool((a as i64) != (b as i64))
}

#[no_mangle]
pub unsafe extern "C" fn int82lt(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_i64(f.args[0].value);
    let b = decode_i16(f.args[1].value);
    encode_bool((a as i64) < (b as i64))
}

#[no_mangle]
pub unsafe extern "C" fn int82le(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_i64(f.args[0].value);
    let b = decode_i16(f.args[1].value);
    encode_bool((a as i64) <= (b as i64))
}

#[no_mangle]
pub unsafe extern "C" fn int82gt(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_i64(f.args[0].value);
    let b = decode_i16(f.args[1].value);
    encode_bool((a as i64) > (b as i64))
}

#[no_mangle]
pub unsafe extern "C" fn int82ge(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_i64(f.args[0].value);
    let b = decode_i16(f.args[1].value);
    encode_bool((a as i64) >= (b as i64))
}

// ─── int48 family (decoder: decode_i32) ──

#[no_mangle]
pub unsafe extern "C" fn int48eq(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_i32(f.args[0].value);
    let b = decode_i64(f.args[1].value);
    encode_bool((a as i64) == (b as i64))
}

#[no_mangle]
pub unsafe extern "C" fn int48ne(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_i32(f.args[0].value);
    let b = decode_i64(f.args[1].value);
    encode_bool((a as i64) != (b as i64))
}

#[no_mangle]
pub unsafe extern "C" fn int48lt(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_i32(f.args[0].value);
    let b = decode_i64(f.args[1].value);
    encode_bool((a as i64) < (b as i64))
}

#[no_mangle]
pub unsafe extern "C" fn int48le(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_i32(f.args[0].value);
    let b = decode_i64(f.args[1].value);
    encode_bool((a as i64) <= (b as i64))
}

#[no_mangle]
pub unsafe extern "C" fn int48gt(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_i32(f.args[0].value);
    let b = decode_i64(f.args[1].value);
    encode_bool((a as i64) > (b as i64))
}

#[no_mangle]
pub unsafe extern "C" fn int48ge(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_i32(f.args[0].value);
    let b = decode_i64(f.args[1].value);
    encode_bool((a as i64) >= (b as i64))
}

// ─── int84 family (decoder: decode_i64) ──

#[no_mangle]
pub unsafe extern "C" fn int84eq(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_i64(f.args[0].value);
    let b = decode_i32(f.args[1].value);
    encode_bool((a as i64) == (b as i64))
}

#[no_mangle]
pub unsafe extern "C" fn int84ne(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_i64(f.args[0].value);
    let b = decode_i32(f.args[1].value);
    encode_bool((a as i64) != (b as i64))
}

#[no_mangle]
pub unsafe extern "C" fn int84lt(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_i64(f.args[0].value);
    let b = decode_i32(f.args[1].value);
    encode_bool((a as i64) < (b as i64))
}

#[no_mangle]
pub unsafe extern "C" fn int84le(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_i64(f.args[0].value);
    let b = decode_i32(f.args[1].value);
    encode_bool((a as i64) <= (b as i64))
}

#[no_mangle]
pub unsafe extern "C" fn int84gt(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_i64(f.args[0].value);
    let b = decode_i32(f.args[1].value);
    encode_bool((a as i64) > (b as i64))
}

#[no_mangle]
pub unsafe extern "C" fn int84ge(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let a = decode_i64(f.args[0].value);
    let b = decode_i32(f.args[1].value);
    encode_bool((a as i64) >= (b as i64))
}
