// Generated by `rules_postgres/lean/Pg/Ir/Emit/Interval.lean`.
// DO NOT EDIT BY HAND. Regenerate via
// `rules_postgres/tools/regen/regen-interval.sh`.
//
// First palloc-using Pg.Ir cluster. Each family emits a pair:
//   1. A `<fn>_internal` Rust fn (the actual algorithm; returns
//      `true` on overflow, writes its &mut out-param).
//   2. The V1 fmgr stub `<fn>` (palloc + delegate + return).
//
// On overflow / infinity-edge errors, both sides set the pg_fcinfo
// TLS flag (FmgrErrorKind::DatetimeValueOutOfRange) and the fmgr
// stub returns Datum 0. The diff-test harness compares the
// (out_datum, err_state) tuple and (on success) the palloc'd
// Interval's field contents.

#![allow(clippy::missing_safety_doc)]

use pg_fcinfo::{
    decode_interval_p, encode_interval_p,
    interval_is_nobegin, interval_is_noend, interval_nobegin, interval_noend,
    interval_not_finite,
    pg_ereport_datetime_value_out_of_range,
    pg_add_s32_overflow, pg_add_s64_overflow,
    pg_sub_s32_overflow, pg_sub_s64_overflow,
    FunctionCallInfoBaseData, Interval, SIZEOF_INTERVAL,
};
use pg_palloc::palloc;

// Internal helper for interval_pl: finite case.
// Both span1 and span2 are guaranteed not to be infinity sentinels.
// Returns true on overflow, false on success (writes result in-place).
unsafe fn finite_interval_pl(span1: &Interval, span2: &Interval, result: &mut Interval) -> bool {
    if pg_add_s32_overflow(span1.month, span2.month, &mut result.month) ||
       pg_add_s32_overflow(span1.day,   span2.day,   &mut result.day) ||
       pg_add_s64_overflow(span1.time,  span2.time,  &mut result.time) ||
       interval_not_finite(result)
    {
        true
    } else {
        false
    }
}

// Internal helper for interval_mi: finite case.
// Both span1 and span2 are guaranteed not to be infinity sentinels.
// Returns true on overflow, false on success (writes result in-place).
unsafe fn finite_interval_mi(span1: &Interval, span2: &Interval, result: &mut Interval) -> bool {
    if pg_sub_s32_overflow(span1.month, span2.month, &mut result.month) ||
       pg_sub_s32_overflow(span1.day,   span2.day,   &mut result.day) ||
       pg_sub_s64_overflow(span1.time,  span2.time,  &mut result.time) ||
       interval_not_finite(result)
    {
        true
    } else {
        false
    }
}

unsafe fn interval_um_internal(interval: &Interval, result: &mut Interval) -> bool {
    if interval_is_nobegin(interval) {
        interval_noend(result);
        false
    } else if interval_is_noend(interval) {
        interval_nobegin(result);
        false
    } else {
        // Negate each field, guarding against overflow.
        let o1 = pg_sub_s64_overflow(0, interval.time,  &mut result.time);
        let o2 = pg_sub_s32_overflow(0, interval.day,   &mut result.day);
        let o3 = pg_sub_s32_overflow(0, interval.month, &mut result.month);
        o1 || o2 || o3 || interval_not_finite(result)
    }
}

#[no_mangle]
pub unsafe extern "C" fn interval_um(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let interval = &*decode_interval_p(f.args[0].value);
    let result_ptr = palloc(SIZEOF_INTERVAL) as *mut Interval;
    if interval_um_internal(interval, &mut *result_ptr) {
        pg_ereport_datetime_value_out_of_range();
        return 0;
    }
    encode_interval_p(result_ptr)
}


#[no_mangle]
pub unsafe extern "C" fn interval_pl(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let span1 = &*decode_interval_p(f.args[0].value);
    let span2 = &*decode_interval_p(f.args[1].value);
    let result_ptr = palloc(SIZEOF_INTERVAL) as *mut Interval;
    if interval_is_nobegin(span1) {
        if interval_is_noend(span2) {
            pg_ereport_datetime_value_out_of_range();
            return 0;
        }
        interval_nobegin(&mut *result_ptr);
    } else if interval_is_noend(span1) {
        if interval_is_nobegin(span2) {
            pg_ereport_datetime_value_out_of_range();
            return 0;
        }
        interval_noend(&mut *result_ptr);
    } else if interval_not_finite(span2) {
        (*result_ptr).time = span2.time;
        (*result_ptr).day = span2.day;
        (*result_ptr).month = span2.month;
    } else {
        if finite_interval_pl(span1, span2, &mut *result_ptr) {
            pg_ereport_datetime_value_out_of_range();
            return 0;
        }
    }
    encode_interval_p(result_ptr)
}


#[no_mangle]
pub unsafe extern "C" fn interval_mi(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let span1 = &*decode_interval_p(f.args[0].value);
    let span2 = &*decode_interval_p(f.args[1].value);
    let result_ptr = palloc(SIZEOF_INTERVAL) as *mut Interval;
    if interval_is_nobegin(span1) {
        if interval_is_nobegin(span2) {
            pg_ereport_datetime_value_out_of_range();
            return 0;
        }
        interval_nobegin(&mut *result_ptr);
    } else if interval_is_noend(span1) {
        if interval_is_noend(span2) {
            pg_ereport_datetime_value_out_of_range();
            return 0;
        }
        interval_noend(&mut *result_ptr);
    } else if interval_is_nobegin(span2) {
        interval_noend(&mut *result_ptr);
    } else if interval_is_noend(span2) {
        interval_nobegin(&mut *result_ptr);
    } else {
        if finite_interval_mi(span1, span2, &mut *result_ptr) {
            pg_ereport_datetime_value_out_of_range();
            return 0;
        }
    }
    encode_interval_p(result_ptr)
}
