// Generated by `rules_postgres/lean/Pg/Ir/Emit/DateArith.lean`.
// DO NOT EDIT BY HAND. Regenerate via
// `rules_postgres/tools/regen/regen-date-arith.sh`.
//
// Date-arithmetic V1 fmgr cluster: 3 functions:
// - date_pli (date + int32 → date): wraps addition, checks for overflow
//   and valid date range.
// - date_mii (date - int32 → date): wraps subtraction, checks for
//   overflow and valid date range.
// - date_mi (date - date → int32): returns elapsed days; rejects
//   infinite operands.
//
// Each body decodes operands, checks DATE_NOT_FINITE (Int32::MIN and
// Int32::MAX sentinels), and on pli/mii checks IS_VALID_DATE. On error
// signals via pg_ereport_datetime_value_out_of_range() + returning
// Datum 0, mirroring Postgres' ereport(ERROR, ...) path.
//
// Attribution: function bodies are PostgreSQL Global Development Group,
// released under the PostgreSQL License (BSD-style).

#![allow(clippy::missing_safety_doc)]

use pg_fcinfo::{
    decode_i32, encode_i32,
    pg_ereport_datetime_value_out_of_range, FunctionCallInfoBaseData,
};

/* Date sentinels: DATEVAL_NOBEGIN = i32::MIN, DATEVAL_NOEND = i32::MAX */
#[inline]
fn is_date_not_finite(d: i32) -> bool {
    d == i32::MIN || d == i32::MAX
}

/* Valid date range: Unix epoch is day 0; Postgres uses days around
 * 1970-01-01 ± ~178 million years. Finite dates must not be sentinels.
 */
#[inline]
fn is_valid_date(d: i32) -> bool {
    d != i32::MIN && d != i32::MAX
}

#[no_mangle]
pub unsafe extern "C" fn date_pli(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let date_val = decode_i32(f.args[0].value);
    let days = decode_i32(f.args[1].value);

    if is_date_not_finite(date_val) {
        return encode_i32(date_val);
    }

    let result = date_val.wrapping_add(days);

    /* Check for integer overflow by sign flip and validate date range. */
    let overflow = if days >= 0 {
        result < date_val
    } else {
        result > date_val
    };

    if overflow || !is_valid_date(result) {
        pg_ereport_datetime_value_out_of_range();
        return 0;
    }

    encode_i32(result)
}

#[no_mangle]
pub unsafe extern "C" fn date_mii(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let date_val = decode_i32(f.args[0].value);
    let days = decode_i32(f.args[1].value);

    if is_date_not_finite(date_val) {
        return encode_i32(date_val);
    }

    let result = date_val.wrapping_sub(days);

    /* Check for integer overflow by sign flip and validate date range. */
    let overflow = if days >= 0 {
        result > date_val
    } else {
        result < date_val
    };

    if overflow || !is_valid_date(result) {
        pg_ereport_datetime_value_out_of_range();
        return 0;
    }

    encode_i32(result)
}

#[no_mangle]
pub unsafe extern "C" fn date_mi(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let date_val1 = decode_i32(f.args[0].value);
    let date_val2 = decode_i32(f.args[1].value);

    if is_date_not_finite(date_val1) || is_date_not_finite(date_val2) {
        pg_ereport_datetime_value_out_of_range();
        return 0;
    }

    encode_i32(date_val1 - date_val2)
}
