// Generated by `rules_postgres/lean/Pg/Ir/Emit/IntHash.lean`.
// DO NOT EDIT BY HAND. Regenerate via
// `rules_postgres/tools/regen/regen-int-hash.sh`.
//
// Integer-type hash V1 fmgr cluster: 12 functions = 6 type
// families × {standard, extended}. Standard variants route through
// pg_fcinfo::hash_bytes_uint32 (mirror of Postgres' Jenkins/lookup3
// hash_bytes_uint32); extended variants take a uint64 seed and
// route through hash_bytes_uint32_extended.

#![allow(clippy::missing_safety_doc)]

use pg_fcinfo::{
    decode_i8, decode_i16, decode_i32, decode_i64, decode_u32,
    encode_u32, encode_u64, hash_bytes_uint32, hash_bytes_uint32_extended,
    FunctionCallInfoBaseData,
};

#[no_mangle]
pub unsafe extern "C" fn hashchar(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let k = decode_i8(f.args[0].value) as i32 as u32;
    encode_u32(hash_bytes_uint32(k))
}

#[no_mangle]
pub unsafe extern "C" fn hashint2(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let k = decode_i16(f.args[0].value) as i32 as u32;
    encode_u32(hash_bytes_uint32(k))
}

#[no_mangle]
pub unsafe extern "C" fn hashint4(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let k = decode_i32(f.args[0].value) as i32 as u32;
    encode_u32(hash_bytes_uint32(k))
}

#[no_mangle]
pub unsafe extern "C" fn hashint8(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let val: i64 = decode_i64(f.args[0].value);
    let lohalf: u32 = val as u32;
    let hihalf: u32 = (val >> 32) as u32;
    let lohalf = lohalf ^ if val >= 0 { hihalf } else { !hihalf };
    encode_u32(hash_bytes_uint32(lohalf))
}

#[no_mangle]
pub unsafe extern "C" fn hashoid(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let k = decode_u32(f.args[0].value);
    encode_u32(hash_bytes_uint32(k))
}

#[no_mangle]
pub unsafe extern "C" fn hashenum(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let k = decode_u32(f.args[0].value);
    encode_u32(hash_bytes_uint32(k))
}

#[no_mangle]
pub unsafe extern "C" fn hashcharextended(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let k = decode_i8(f.args[0].value) as i32 as u32;
    let seed: u64 = decode_i64(f.args[1].value) as u64;
    encode_u64(hash_bytes_uint32_extended(k, seed))
}

#[no_mangle]
pub unsafe extern "C" fn hashint2extended(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let k = decode_i16(f.args[0].value) as i32 as u32;
    let seed: u64 = decode_i64(f.args[1].value) as u64;
    encode_u64(hash_bytes_uint32_extended(k, seed))
}

#[no_mangle]
pub unsafe extern "C" fn hashint4extended(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let k = decode_i32(f.args[0].value) as i32 as u32;
    let seed: u64 = decode_i64(f.args[1].value) as u64;
    encode_u64(hash_bytes_uint32_extended(k, seed))
}

#[no_mangle]
pub unsafe extern "C" fn hashint8extended(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let val: i64 = decode_i64(f.args[0].value);
    let lohalf: u32 = val as u32;
    let hihalf: u32 = (val >> 32) as u32;
    let lohalf = lohalf ^ if val >= 0 { hihalf } else { !hihalf };
    let seed: u64 = decode_i64(f.args[1].value) as u64;
    encode_u64(hash_bytes_uint32_extended(lohalf, seed))
}

#[no_mangle]
pub unsafe extern "C" fn hashoidextended(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let k = decode_u32(f.args[0].value);
    let seed: u64 = decode_i64(f.args[1].value) as u64;
    encode_u64(hash_bytes_uint32_extended(k, seed))
}

#[no_mangle]
pub unsafe extern "C" fn hashenumextended(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let k = decode_u32(f.args[0].value);
    let seed: u64 = decode_i64(f.args[1].value) as u64;
    encode_u64(hash_bytes_uint32_extended(k, seed))
}
