// Generated by `rules_postgres/lean/Pg/Ir/Emit/FloatUnary.lean`.
// DO NOT EDIT BY HAND. Regenerate via
// `rules_postgres/tools/regen/regen-float-unary.sh`.
//
// Float unary V1 fmgr cluster: 4 functions = {um, abs} × {float4, float8}.
// Each body decodes the single argument, applies the operation (abs via
// f32::abs()/f64::abs(), um via negation), and encodes the result.
// No ereport or special NaN handling — standard IEEE-754 semantics.

#![allow(clippy::missing_safety_doc)]

use pg_fcinfo::{
    decode_f32, decode_f64,
    encode_f32, encode_f64,
    FunctionCallInfoBaseData,
};

#[no_mangle]
pub unsafe extern "C" fn float4abs(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg = decode_f32(f.args[0].value);
    encode_f32(arg.abs())
}

#[no_mangle]
pub unsafe extern "C" fn float8abs(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg = decode_f64(f.args[0].value);
    encode_f64(arg.abs())
}

#[no_mangle]
pub unsafe extern "C" fn float4um(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg = decode_f32(f.args[0].value);
    let result: f32 = -arg;
    encode_f32(result)
}

#[no_mangle]
pub unsafe extern "C" fn float8um(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg = decode_f64(f.args[0].value);
    let result: f64 = -arg;
    encode_f64(result)
}
