// Generated by `rules_postgres/lean/Pg/Ir/Emit/FloatToInt.lean`.
// DO NOT EDIT BY HAND. Regenerate via
// `rules_postgres/tools/regen/regen-float-to-int.sh`.
//
// Float-to-int cast V1 fmgr cluster: 4 functions = {ftoi2, ftoi4, dtoi2, dtoi4}.
// Each body decodes a float argument, rounds it via rint(), checks for NaN
// and out-of-range values, and returns the truncated int result.

#![allow(clippy::missing_safety_doc)]

use pg_fcinfo::{
    decode_f32, decode_f64,
    encode_i16, encode_i32,
    pg_ereport_numeric_value_out_of_range,
    FunctionCallInfoBaseData,
};

/// Banker's rounding (round to nearest, ties to even) — matches C's rint().
fn rint_f32(x: f32) -> f32 {
    let truncated = x.trunc();
    let frac = x - truncated;
    if frac == 0.5 {
        let int_part = truncated as i32;
        if int_part % 2 == 0 {
            truncated
        } else {
            truncated + 1.0
        }
    } else if frac == -0.5 {
        let int_part = truncated as i32;
        if int_part % 2 == 0 {
            truncated
        } else {
            truncated - 1.0
        }
    } else {
        x.round()
    }
}

/// Banker's rounding (round to nearest, ties to even) — matches C's rint().
fn rint_f64(x: f64) -> f64 {
    let truncated = x.trunc();
    let frac = x - truncated;
    if frac == 0.5 {
        let int_part = truncated as i64;
        if int_part % 2 == 0 {
            truncated
        } else {
            truncated + 1.0
        }
    } else if frac == -0.5 {
        let int_part = truncated as i64;
        if int_part % 2 == 0 {
            truncated
        } else {
            truncated - 1.0
        }
    } else {
        x.round()
    }
}

#[no_mangle]
pub unsafe extern "C" fn ftoi2(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let mut num = decode_f32(f.args[0].value);
    num = rint_f32(num);
    if num.is_nan() || num < -32768.0 || num > 32767.0 {
        pg_ereport_numeric_value_out_of_range();
        return 0;
    }
    encode_i16(num as i16)
}

#[no_mangle]
pub unsafe extern "C" fn ftoi4(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let mut num = decode_f32(f.args[0].value);
    num = rint_f32(num);
    if num.is_nan() || num < -2147483648.0 || num > 2147483647.0 {
        pg_ereport_numeric_value_out_of_range();
        return 0;
    }
    encode_i32(num as i32)
}

#[no_mangle]
pub unsafe extern "C" fn dtoi2(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let mut num = decode_f64(f.args[0].value);
    num = rint_f64(num);
    if num.is_nan() || num < -32768.0 || num > 32767.0 {
        pg_ereport_numeric_value_out_of_range();
        return 0;
    }
    encode_i16(num as i16)
}

#[no_mangle]
pub unsafe extern "C" fn dtoi4(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let mut num = decode_f64(f.args[0].value);
    num = rint_f64(num);
    if num.is_nan() || num < -2147483648.0 || num > 2147483647.0 {
        pg_ereport_numeric_value_out_of_range();
        return 0;
    }
    encode_i32(num as i32)
}
