/*
 * Generated by `rules_postgres/lean/Pg/Ir/Emit/CashArithC.lean`.
 * DO NOT EDIT BY HAND. Regenerate via
 * `rules_postgres/tools/regen/check-cash-arith-grounding.sh`.
 *
 * This file exists to be `clang -ast-dump=json`-ed alongside
 * real `src/backend/utils/adt/cash.c` and structurally
 * diffed function-by-function. A passing diff means the Lean spec
 * captures the same algorithm Postgres wrote.
 */

#include "postgres.h"

#include <limits.h>
#include <ctype.h>
#include <math.h>

#include "common/int.h"
#include "libpq/pqformat.h"
#include "utils/builtins.h"
#include "utils/cash.h"
#include "utils/float.h"
#include "utils/numeric.h"
#include "utils/pg_locale.h"

static inline Cash
cash_pl_cash(Cash c1, Cash c2)
{
	Cash		res;

	if (unlikely(pg_add_s64_overflow(c1, c2, &res)))
		ereport(ERROR,
				(errcode(ERRCODE_NUMERIC_VALUE_OUT_OF_RANGE),
				 errmsg("money out of range")));

	return res;
}

Datum
cash_pl(PG_FUNCTION_ARGS)
{
	Cash		arg1 = PG_GETARG_CASH(0);
	Cash		arg2 = PG_GETARG_CASH(1);

	PG_RETURN_CASH(cash_pl_cash(arg1, arg2));
}

static inline Cash
cash_mi_cash(Cash c1, Cash c2)
{
	Cash		res;

	if (unlikely(pg_sub_s64_overflow(c1, c2, &res)))
		ereport(ERROR,
				(errcode(ERRCODE_NUMERIC_VALUE_OUT_OF_RANGE),
				 errmsg("money out of range")));

	return res;
}

Datum
cash_mi(PG_FUNCTION_ARGS)
{
	Cash		arg1 = PG_GETARG_CASH(0);
	Cash		arg2 = PG_GETARG_CASH(1);

	PG_RETURN_CASH(cash_mi_cash(arg1, arg2));
}

static inline Cash
cash_mul_int64(Cash c1, int64 c2)
{
	Cash		res;

	if (unlikely(pg_mul_s64_overflow(c1, (int64) c2, &res)))
		ereport(ERROR,
				(errcode(ERRCODE_NUMERIC_VALUE_OUT_OF_RANGE),
				 errmsg("money out of range")));

	return res;
}

Datum
cash_mul_int4(PG_FUNCTION_ARGS)
{
	Cash		arg1 = PG_GETARG_CASH(0);
	int32		arg2 = PG_GETARG_INT32(1);

	PG_RETURN_CASH(cash_mul_int64(arg1, (int64) arg2));
}

static inline Cash
cash_div_int64(Cash c, int64 i)
{
	if (unlikely(i == 0))
		ereport(ERROR,
				(errcode(ERRCODE_DIVISION_BY_ZERO),
				 errmsg("division by zero")));

	return c / (int64) i;
}

Datum
cash_div_int4(PG_FUNCTION_ARGS)
{
	Cash		c = PG_GETARG_CASH(0);
	int32		i = PG_GETARG_INT32(1);

	PG_RETURN_CASH(cash_div_int64(c, (int64) i));
}

Datum
cashlarger(PG_FUNCTION_ARGS)
{
	Cash		c1 = PG_GETARG_CASH(0);
	Cash		c2 = PG_GETARG_CASH(1);
	Cash		result;

	result = (c1 > c2) ? c1 : c2;

	PG_RETURN_CASH(result);
}

Datum
cashsmaller(PG_FUNCTION_ARGS)
{
	Cash		c1 = PG_GETARG_CASH(0);
	Cash		c2 = PG_GETARG_CASH(1);
	Cash		result;

	result = (c1 < c2) ? c1 : c2;

	PG_RETURN_CASH(result);
}
