/*
 * renamed_cash_arith.c — rename each vendored fmgr body to <fn>_orig
 * before compiling, so the test linker doesn't merge them with the
 * Rust crate's #[no_mangle] symbols. Mirrors pg_int4_arith's
 * renamed_int4_arith.c.
 *
 * Generated by hand to stay in sync with the family table in
 * `rules_postgres/lean/Pg/Ir/Emit/CashArithCommon.lean`.
 */

#define cash_pl       cash_pl_orig
#define cash_mi       cash_mi_orig
#define cash_mul_int4 cash_mul_int4_orig
#define cash_div_int4 cash_div_int4_orig
#define cashlarger    cashlarger_orig
#define cashsmaller   cashsmaller_orig

#include "cash_arith.c"
