// Generated by `rules_postgres/lean/Pg/Ir/Emit/IntBitwise.lean`.
// DO NOT EDIT BY HAND. Regenerate via
// `rules_postgres/tools/regen/regen-int-bitwise.sh`.
//
// 18 functions = 6 ops × 3 widths.
// {and, or, xor} × {int2, int4, int8} — binary same-type.
// {not}            × {int2, int4, int8} — unary.
// {shl, shr}       × {int2, int4, int8} — binary with int32 shift count.
//
// Pure: no ereport, no palloc. Shifts use wrapping_shl/_shr to
// match C's x86_64 mod-width semantics across all arg2 values.

#![allow(clippy::missing_safety_doc)]

use pg_fcinfo::{
    decode_i16, decode_i32, decode_i64,
    encode_i16, encode_i32, encode_i64,
    FunctionCallInfoBaseData,
};

#[no_mangle]
pub unsafe extern "C" fn int2and(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg1 = decode_i16(f.args[0].value);
    let arg2 = decode_i16(f.args[1].value);
    encode_i16(arg1 & arg2)
}

#[no_mangle]
pub unsafe extern "C" fn int2or(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg1 = decode_i16(f.args[0].value);
    let arg2 = decode_i16(f.args[1].value);
    encode_i16(arg1 | arg2)
}

#[no_mangle]
pub unsafe extern "C" fn int2xor(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg1 = decode_i16(f.args[0].value);
    let arg2 = decode_i16(f.args[1].value);
    encode_i16(arg1 ^ arg2)
}

#[no_mangle]
pub unsafe extern "C" fn int2not(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg1 = decode_i16(f.args[0].value);
    encode_i16(!arg1)
}

#[no_mangle]
pub unsafe extern "C" fn int2shl(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg1 = decode_i16(f.args[0].value);
    let arg2 = decode_i32(f.args[1].value);
    encode_i16(arg1.wrapping_shl(arg2 as u32))
}

#[no_mangle]
pub unsafe extern "C" fn int2shr(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg1 = decode_i16(f.args[0].value);
    let arg2 = decode_i32(f.args[1].value);
    encode_i16(arg1.wrapping_shr(arg2 as u32))
}

#[no_mangle]
pub unsafe extern "C" fn int4and(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg1 = decode_i32(f.args[0].value);
    let arg2 = decode_i32(f.args[1].value);
    encode_i32(arg1 & arg2)
}

#[no_mangle]
pub unsafe extern "C" fn int4or(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg1 = decode_i32(f.args[0].value);
    let arg2 = decode_i32(f.args[1].value);
    encode_i32(arg1 | arg2)
}

#[no_mangle]
pub unsafe extern "C" fn int4xor(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg1 = decode_i32(f.args[0].value);
    let arg2 = decode_i32(f.args[1].value);
    encode_i32(arg1 ^ arg2)
}

#[no_mangle]
pub unsafe extern "C" fn int4not(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg1 = decode_i32(f.args[0].value);
    encode_i32(!arg1)
}

#[no_mangle]
pub unsafe extern "C" fn int4shl(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg1 = decode_i32(f.args[0].value);
    let arg2 = decode_i32(f.args[1].value);
    encode_i32(arg1.wrapping_shl(arg2 as u32))
}

#[no_mangle]
pub unsafe extern "C" fn int4shr(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg1 = decode_i32(f.args[0].value);
    let arg2 = decode_i32(f.args[1].value);
    encode_i32(arg1.wrapping_shr(arg2 as u32))
}

#[no_mangle]
pub unsafe extern "C" fn int8and(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg1 = decode_i64(f.args[0].value);
    let arg2 = decode_i64(f.args[1].value);
    encode_i64(arg1 & arg2)
}

#[no_mangle]
pub unsafe extern "C" fn int8or(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg1 = decode_i64(f.args[0].value);
    let arg2 = decode_i64(f.args[1].value);
    encode_i64(arg1 | arg2)
}

#[no_mangle]
pub unsafe extern "C" fn int8xor(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg1 = decode_i64(f.args[0].value);
    let arg2 = decode_i64(f.args[1].value);
    encode_i64(arg1 ^ arg2)
}

#[no_mangle]
pub unsafe extern "C" fn int8not(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg1 = decode_i64(f.args[0].value);
    encode_i64(!arg1)
}

#[no_mangle]
pub unsafe extern "C" fn int8shl(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg1 = decode_i64(f.args[0].value);
    let arg2 = decode_i32(f.args[1].value);
    encode_i64(arg1.wrapping_shl(arg2 as u32))
}

#[no_mangle]
pub unsafe extern "C" fn int8shr(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {
    let f = &mut *fcinfo;
    let arg1 = decode_i64(f.args[0].value);
    let arg2 = decode_i32(f.args[1].value);
    encode_i64(arg1.wrapping_shr(arg2 as u32))
}
