/* Generated by `rules_postgres/lean/Pg/Ir/Emit/UuidC.lean`. */
/* DO NOT EDIT BY HAND. Regenerate via */
/* `rules_postgres/tools/regen/regen-uuid.sh`. */

#include <string.h>
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

/* Minimal Postgres type definitions for the standalone C oracle. */
typedef unsigned int Oid;
typedef uintptr_t Datum;
typedef void *fmNodePtr;
#define FLEXIBLE_ARRAY_MEMBER
#define UUID_LEN 16
#define WORDS_BIGENDIAN 0

typedef int16_t int16;
typedef int32_t int32;
typedef int64_t int64;
typedef uint32_t uint32;
typedef uint64_t uint64;

typedef struct
{
	unsigned char data[UUID_LEN];
} pg_uuid_t;

typedef struct NullableDatum
{
	Datum value;
	bool isnull;
} NullableDatum;

struct FmgrInfo;

typedef struct FunctionCallInfoBaseData
{
	struct FmgrInfo *flinfo;
	fmNodePtr context;
	fmNodePtr resultinfo;
	Oid fncollation;
	bool isnull;
	short nargs;
	NullableDatum args[FLEXIBLE_ARRAY_MEMBER];
} FunctionCallInfoBaseData;

/* V1 fmgr calling convention macros. */
#define DatumGetPointer(x) ((void *) (uintptr_t) (x))
#define PG_FUNCTION_ARGS FunctionCallInfoBaseData *fcinfo
#define PG_GETARG_UUID_P(n) ((pg_uuid_t *) DatumGetPointer(fcinfo->args[n].value))
#define PG_GETARG_INT64(n) ((int64) (fcinfo->args[n].value))
#define PG_RETURN_BOOL(x) return (Datum)((x) ? 1 : 0)
#define PG_RETURN_INT32(x) return (Datum) (uint32_t) (x)

/* Hash function stubs (matching Postgres signature). */
extern Datum hash_any(const unsigned char *k, int keylen);
extern Datum hash_any_extended(const unsigned char *k, int keylen, uint64 seed);

/* Forward declaration of the static helper. */
static int uuid_internal_cmp(const pg_uuid_t *arg1, const pg_uuid_t *arg2);

static int
uuid_internal_cmp(const pg_uuid_t *arg1, const pg_uuid_t *arg2)
{
	return memcmp(arg1->data, arg2->data, UUID_LEN);
}


Datum
uuid_eq(PG_FUNCTION_ARGS)
{
	pg_uuid_t  *arg1 = PG_GETARG_UUID_P(0);
	pg_uuid_t  *arg2 = PG_GETARG_UUID_P(1);

	PG_RETURN_BOOL(uuid_internal_cmp(arg1, arg2) == 0);
}

Datum
uuid_ne(PG_FUNCTION_ARGS)
{
	pg_uuid_t  *arg1 = PG_GETARG_UUID_P(0);
	pg_uuid_t  *arg2 = PG_GETARG_UUID_P(1);

	PG_RETURN_BOOL(uuid_internal_cmp(arg1, arg2) != 0);
}

Datum
uuid_lt(PG_FUNCTION_ARGS)
{
	pg_uuid_t  *arg1 = PG_GETARG_UUID_P(0);
	pg_uuid_t  *arg2 = PG_GETARG_UUID_P(1);

	PG_RETURN_BOOL(uuid_internal_cmp(arg1, arg2) < 0);
}

Datum
uuid_le(PG_FUNCTION_ARGS)
{
	pg_uuid_t  *arg1 = PG_GETARG_UUID_P(0);
	pg_uuid_t  *arg2 = PG_GETARG_UUID_P(1);

	PG_RETURN_BOOL(uuid_internal_cmp(arg1, arg2) <= 0);
}

Datum
uuid_gt(PG_FUNCTION_ARGS)
{
	pg_uuid_t  *arg1 = PG_GETARG_UUID_P(0);
	pg_uuid_t  *arg2 = PG_GETARG_UUID_P(1);

	PG_RETURN_BOOL(uuid_internal_cmp(arg1, arg2) > 0);
}

Datum
uuid_ge(PG_FUNCTION_ARGS)
{
	pg_uuid_t  *arg1 = PG_GETARG_UUID_P(0);
	pg_uuid_t  *arg2 = PG_GETARG_UUID_P(1);

	PG_RETURN_BOOL(uuid_internal_cmp(arg1, arg2) >= 0);
}

Datum
uuid_cmp(PG_FUNCTION_ARGS)
{
	pg_uuid_t  *arg1 = PG_GETARG_UUID_P(0);
	pg_uuid_t  *arg2 = PG_GETARG_UUID_P(1);

	PG_RETURN_INT32(uuid_internal_cmp(arg1, arg2));
}


Datum
uuid_hash(PG_FUNCTION_ARGS)
{
	pg_uuid_t  *key = PG_GETARG_UUID_P(0);

	return hash_any(key->data, UUID_LEN);
}

Datum
uuid_hash_extended(PG_FUNCTION_ARGS)
{
	pg_uuid_t  *key = PG_GETARG_UUID_P(0);

	return hash_any_extended(key->data, UUID_LEN, PG_GETARG_INT64(1));
}
